"use client";
import {FormEvent,useEffect,useState} from 'react';
import {getSession,signIn,signOut,registerTeacher,verifyEmail,apiFetch,setSession} from '@/lib/supabase-client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import TeacherReview from './teacher-review';
export default function AuthGate({children}:{children:React.ReactNode}){
 const [ready,setReady]=useState(false),[checking,setChecking]=useState(true),[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[school,setSchool]=useState(''),[subjects,setSubjects]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[access,setAccess]=useState<any>(null),[review,setReview]=useState(false);
 async function check(){const r=await apiFetch('/api/teachers');const d:any=await r.json();if(!r.ok){if(r.status===401){setSession(null);setReady(false);return}throw Error(d.error)}setAccess(d);setReady(true)}
 useEffect(()=>{if(getSession()?.access_token)check().catch(e=>setError(e.message)).finally(()=>setChecking(false));else setChecking(false)},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{
 if(mode==='register'){if(password.length<8)throw Error('密碼至少需要 8 個字元');const d:any=await registerTeacher(email.trim(),password,{name:name.trim(),school:school.trim(),subjects:subjects.trim()});setPassword('');if(d.access_token){await check()}else{setMode('verify');setNotice('請至 Email 開啟驗證信，再回到本頁登入；若信件提供驗證碼，也可在下方輸入。完成驗證後仍需管理員核准。')}}
 else if(mode==='verify'){await verifyEmail(email.trim(),code.trim());await check()}
 else{await signIn(email.trim(),password);setPassword('');await check()}
 }catch(x:any){setError(x.message||'操作失敗')}finally{setBusy(false)}}
 if(checking)return <main className="auth-page"><section className="auth-card">正在確認登入狀態…</section></main>;
 if(ready&&!access?.profile&&!access?.admin)return <main className="auth-page"><section className="auth-card"><h1>提交教師申請</h1><p>您已登入。請填寫任教資料，提交後由管理員審核。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await apiFetch('/api/teachers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,school,subjects})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await check()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label>姓名<Input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>任教學校／單位<Input value={school} onChange={e=>setSchool(e.target.value)} required maxLength={150}/></label><label>任教科目／輔導職務<Input value={subjects} onChange={e=>setSubjects(e.target.value)} required maxLength={200}/></label>{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>提交老師註冊申請</Button><Button type="button" variant="outline" onClick={signOut}>登出</Button></form></section></main>;
 if(ready&&!access?.approved)return <main className="auth-page"><section className="auth-card"><h1>{access?.profile?.status==='rejected'?'教師申請未核准':'教師申請待審核'}</h1><p>{access?.profile?.name||'此帳號'}：{access?.profile?.status==='rejected'?'請聯絡 LTU 管理員確認申請。':'管理員核准後，您即可使用升學輔導工作台。'}</p>{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={async()=>{setBusy(true);try{await check()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>重新確認審核狀態</Button><Button variant="outline" onClick={signOut}>登出</Button></section></main>;
 if(!ready)return <main className="auth-page"><section className="auth-card"><div className="eyebrow">LTU EDUCATION · COUNSELLING</div><h1>LTU OSSD 升學輔導資料庫</h1><div className="auth-modes"><Button variant={mode==='login'?'default':'outline'} onClick={()=>{setMode('login');setError('');setNotice('')}}>教師／管理員登入</Button><Button variant={mode==='register'?'default':'outline'} onClick={()=>{setMode('register');setError('');setNotice('')}}>老師註冊</Button></div><p>{mode==='register'?'填寫教師資料提出申請，經管理員核准後開通。若此 Email 已註冊過，請先登入再提交教師申請。':mode==='verify'?'完成 Email 驗證':'已核准的老師及管理員可登入使用。'}</p><form onSubmit={submit}>
 {mode==='register'&&<><label>姓名<Input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>任教學校／單位<Input value={school} onChange={e=>setSchool(e.target.value)} required maxLength={150}/></label><label>任教科目／輔導職務<Input value={subjects} onChange={e=>setSubjects(e.target.value)} required maxLength={200}/></label></>}
 <label>Email<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label>
 {mode==='verify'?<label>驗證碼<Input value={code} onChange={e=>setCode(e.target.value)} required autoComplete="one-time-code"/></label>:<label>密碼<Input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={mode==='register'?8:undefined} autoComplete={mode==='register'?'new-password':'current-password'}/></label>}
 {error&&<p className="notice" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<Button type="submit" disabled={busy}>{busy?'處理中…':mode==='register'?'提交老師註冊申請':mode==='verify'?'驗證 Email':'登入管理系統'}</Button></form></section></main>;
 return <><div className="auth-toolbar">{access?.admin&&<Button variant="outline" onClick={()=>setReview(!review)}>{review?'返回升學輔導':'老師註冊審核'}</Button>}<Button variant="outline" onClick={signOut}>登出</Button></div>{review?<main className="teacher-review"><TeacherReview/></main>:children}</>
}
