(function(){'use strict';
const PENDING='ltuCapPendingPracticeV1';
const MOCK='ltuCapMockResumeV1';
let replaying=false,mockSeq=0,mockCapture=[],mockCaptureTs=0,resumeTimer=null;
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<8;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
function dispatch(name,detail){window.dispatchEvent(new CustomEvent(name,{detail}))}
async function authMe(){try{const r=await fetch('/api/auth/me',{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
function savePending(detail){try{sessionStorage.setItem(PENDING,JSON.stringify({detail:detail||{mode:'core'},ts:Date.now()}))}catch{}}
function takePending(){try{const raw=sessionStorage.getItem(PENDING);if(!raw)return null;const x=JSON.parse(raw);if(!x?.ts||Date.now()-x.ts>10*60*1000){sessionStorage.removeItem(PENDING);return null}sessionStorage.removeItem(PENDING);return x.detail||{mode:'core'}}catch{return null}}
function practiceInProgress(d){const m=d?.getElementById('ltuPracticeModalV4');if(!m?.classList.contains('show'))return false;const t=(m.textContent||'');return /第\s*\d+\s*\/\s*\d+\s*題/.test(t)&&!/練習完成|訓練完成|已完成/.test(t)}
function readMock(){try{const x=JSON.parse(localStorage.getItem(MOCK)||'null');if(!x||!Array.isArray(x.ids)||x.ids.length!==64)return null;if(Date.now()-(x.ts||0)>48*60*60*1000){localStorage.removeItem(MOCK);return null}return x}catch{return null}}
function saveMock(x){try{x.ts=Date.now();localStorage.setItem(MOCK,JSON.stringify(x))}catch{}}
function clearMock(){try{localStorage.removeItem(MOCK)}catch{}}
function mockInProgress(d){return !!(d?.querySelector('#pcMock .pcMock')&&!d.querySelector('#pcMock .pcResult'))||!!readMock()}
function confirmLeavePractice(d){return !practiceInProgress(d)||confirm('目前這輪練習還沒完成。離開後本輪作答畫面不會保留，確定要離開嗎？')}
function bindPracticeGuard(d){if(!d?.body||d.body.dataset.practiceGuardV1)return;d.body.dataset.practiceGuardV1='1';d.addEventListener('click',e=>{const m=d.getElementById('ltuPracticeModalV4');if(!m?.classList.contains('show'))return;const close=e.target?.closest?.('.lp4close');const backdrop=e.target===m;if((close||backdrop)&&!confirmLeavePractice(d)){e.preventDefault();e.stopImmediatePropagation()}},true)}
function installMockCapture(){const eng=window.LTUQuestionEngine;if(!eng||eng.__resumeWrapped||typeof eng.getBatch!=='function')return;const orig=eng.getBatch.bind(eng),pattern=[[12,'vocabulary'],[7,'grammar'],[4,'cloze'],[20,'detail'],[21,'listening']];eng.getBatch=function(args={}){const out=orig(args);const first=Array.isArray(args.types)&&args.types[0]||'';const exp=pattern[mockSeq];const now=Date.now();if(!exp||now-mockCaptureTs>5000||Number(args.count)!==exp[0]||first!==exp[1]){mockSeq=0;mockCapture=[]}const cur=pattern[mockSeq];if(cur&&Number(args.count)===cur[0]&&first===cur[1]){if(mockSeq===0)mockCapture=[];mockCapture.push(...out);mockCaptureTs=now;mockSeq++;if(mockSeq===5&&mockCapture.length===64){saveMock({ids:mockCapture.map(q=>q.id),ans:{},plays:{},part:'reading',idx:0,left:3600,startedAt:Date.now(),ts:Date.now()});mockSeq=0;mockCapture=[]}}return out};eng.__resumeWrapped=true}
function syncMockFromDom(d){const s=readMock(),app=d?.getElementById('pcMock');if(!s||!app?.querySelector('.pcMock'))return;const top=app.querySelector('.pcTop');if(top){const bs=top.querySelectorAll('b'),label=bs[0]?.textContent||'',tm=bs[1]?.textContent||'';s.part=label.includes('聽力')?'listening':'reading';const m=tm.match(/(\d+):(\d+)/);if(m)s.left=Number(m[1])*60+Number(m[2])}saveMock(s)}
function bindMockCapture(d){if(!d?.body||d.body.dataset.mockResumeCapture)return;d.body.dataset.mockResumeCapture='1';d.addEventListener('click',e=>{const app=e.target?.closest?.('#pcMock');if(!app)return;const s=readMock();if(!s)return;const op=e.target.closest?.('[data-op]'),num=e.target.closest?.('[data-n]');if(op)s.ans[s.idx]=Number(op.dataset.op);if(num)s.idx=Number(num.dataset.n);if(e.target.closest?.('[data-prev]'))s.idx=Math.max(s.part==='reading'?0:43,s.idx-1);if(e.target.closest?.('[data-next]'))s.idx=Math.min(s.part==='reading'?42:63,s.idx+1);if(e.target.closest?.('[data-switch]')){s.part='listening';s.idx=43;s.left=1500}s.ts=Date.now();saveMock(s);setTimeout(()=>syncMockFromDom(d),20)},true);new MutationObserver(()=>{if(d.querySelector('#pcMock .pcResult'))clearMock()}).observe(d.body,{childList:true,subtree:true})}
function qFromId(id){const eng=window.LTUQuestionEngine,n=Number(String(id).split('-').pop())-1;return eng?.make?.(n)}
function renderResume(d,s){const app=d.getElementById('pcMock');if(!app)return;const qs=s.ids.map(qFromId);if(qs.some(x=>!x)){clearMock();return alert('無法恢復這份模考，請重新開始。')}if(resumeTimer)clearInterval(resumeTimer);let idx=Math.max(0,Math.min(63,Number(s.idx)||0)),ans=s.ans||{},plays=s.plays||{},part=s.part==='listening'?'listening':'reading',left=Math.max(1,Number(s.left)||(part==='reading'?3600:1500));function persist(){saveMock({ids:s.ids,ans,plays,part,idx,left,startedAt:s.startedAt||Date.now(),ts:Date.now()})}function draw(){const st=part==='reading'?0:43,en=part==='reading'?43:64;if(idx<st||idx>=en)idx=st;const q=qs[idx],done=Object.keys(ans).filter(k=>+k>=st&&+k<en).length;app.innerHTML=`<div class="pcMock"><div class="pcTop"><b>${part==='reading'?'第一節｜閱讀':'第二節｜聽力'} ${done}/${en-st}</b><b>${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}</b></div><div class="pcStem">${q.stem}</div>${q.meta.audioText?'<button class="pcBtn sec" data-audio>▶ 播放聽力（最多 2 次）</button>':''}<div class="pcOpts">${q.options.map((x,i)=>`<button class="pcOpt ${ans[idx]===i?'sel':''}" data-op="${i}">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}</div><div class="pcNav">${qs.slice(st,en).map((_,i)=>{const n=st+i;return`<button class="pcNum ${ans[n]!=null?'done':''}" data-n="${n}">${n+1}</button>`}).join('')}</div><div class="pcActions"><button class="pcBtn sec" data-prev>上一題</button>${part==='reading'?'<button class="pcBtn" data-switch>進入聽力</button>':'<button class="pcBtn" data-submit>交卷</button>'}<button class="pcBtn sec" data-next>下一題</button></div></div>`;app.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{ans[idx]=Number(b.dataset.op);persist();draw()});app.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.n);persist();draw()});app.querySelector('[data-prev]').onclick=()=>{idx=Math.max(st,idx-1);persist();draw()};app.querySelector('[data-next]').onclick=()=>{idx=Math.min(en-1,idx+1);persist();draw()};const au=app.querySelector('[data-audio]');if(au)au.onclick=()=>{plays[idx]=plays[idx]||0;if(plays[idx]>=2)return alert('本題最多播放 2 次。');plays[idx]++;persist();speechSynthesis.cancel();const v=new SpeechSynthesisUtterance(q.meta.audioText);v.lang='en-US';v.rate=.9;speechSynthesis.speak(v)};const sw=app.querySelector('[data-switch]');if(sw)sw.onclick=()=>{const miss=Array.from({length:43},(_,i)=>i).filter(i=>ans[i]==null).length;if(miss&&!confirm(`閱讀還有 ${miss} 題未作答，仍要進入聽力嗎？`))return;part='listening';idx=43;left=1500;persist();draw()};const su=app.querySelector('[data-submit]');if(su)su.onclick=submit;persist()}
async function submit(){const miss=Array.from({length:64},(_,i)=>i).filter(i=>ans[i]==null).length;if(miss&&!confirm(`還有 ${miss} 題未作答，確定交卷嗎？`))return;if(resumeTimer)clearInterval(resumeTimer);const items=qs.map((q,i)=>({id:q.id,type:q.type,competency:q.meta.competency,grammarFocus:q.meta.grammarFocus,selectedIndex:ans[i]??null,answer:q.answer,correct:ans[i]===q.answer,stem:q.stem,options:q.options,explanation:q.explanation}));app.innerHTML='<div class="pcLock">正在同步模考與 AI 學習記憶…</div>';let r;try{r=await fetch('/api/progress/mock',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})})}catch{}if(!r?.ok){persist();app.innerHTML='<div class="pcLock"><h3>同步失敗</h3><p>你的模考進度已保留，不需要重做。</p><button class="pcBtn" data-retry>重試同步</button></div>';app.querySelector('[data-retry]').onclick=submit;return}const x=await r.json();clearMock();app.innerHTML=`<div class="pcResult"><h3>本週 AI 學習診斷</h3><div class="pcStats"><div class="pcStat"><small>閱讀</small><b>${x.readingCorrect}/43</b></div><div class="pcStat"><small>聽力</small><b>${x.listeningCorrect}/21</b></div><div class="pcStat"><small>整體</small><b>${x.scorePercent}%</b></div><div class="pcStat"><small>需補強</small><b>${64-x.totalCorrect}</b></div></div><p class="pcSub">錯題已同步 AI 筆記與弱點模型。</p><button class="pcBtn" data-after>做 10 題弱點訓練</button></div>`;app.querySelector('[data-after]').onclick=()=>dispatch('ltu:start-practice',{mode:'extra'});dispatch('ltu:product-refresh')}
resumeTimer=setInterval(()=>{left--;if(left<=0){if(part==='reading'){part='listening';idx=43;left=1500;persist();draw()}else submit()}else if(left%5===0)persist();const b=app.querySelector('.pcTop b:last-child');if(b)b.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`},1000);draw();app.scrollIntoView({behavior:'smooth',block:'start'})}
function bindResumeButton(d){const s=readMock(),btn=d?.querySelector('#weekly [data-mock]');if(!btn)return;if(s){const done=Object.keys(s.ans||{}).length;btn.textContent=`繼續未完成模考（${done}/64）`;btn.dataset.resumeBound='1';btn.onclick=e=>{e.preventDefault();renderResume(d,readMock())}}else if(btn.dataset.resumeBound){btn.textContent='開始本週模考';btn.removeAttribute('data-resume-bound')}}
function cleanup(d){if(!d?.body)return;installMockCapture();bindPracticeGuard(d);bindMockCapture(d);bindResumeButton(d);syncMockFromDom(d);const hero=d.querySelector('.hero');if(hero){const lead=hero.querySelector('.lead');if(lead)lead.textContent='免費會員每天 3 題＋基本解析；AI Complete 每日 10 題核心任務，可追加弱點訓練，並串接 AI 筆記、Weekly Mock、歷屆能力練習與弱點分析。';const stats=hero.querySelectorAll('.stat');const vals=[['3','免費會員每日題數'],['10+','Complete 核心＋追加訓練'],['43+21','Weekly Mock'],['20K','原創動態題目變化']];stats.forEach((x,i)=>{if(!vals[i])return;const b=x.querySelector('b'),s=x.querySelector('span');if(b)b.textContent=vals[i][0];if(s)s.textContent=vals[i][1]});const primary=hero.querySelector('.btn.primary');if(primary&&!primary.dataset.launchv2){const n=primary.cloneNode(true);n.dataset.launchv2='1';n.dataset.authv2='1';n.removeAttribute('onclick');n.textContent='免費開始 3 題';n.addEventListener('click',e=>{e.preventDefault();dispatch('ltu:start-practice',{mode:'core'})});primary.replaceWith(n)}const secondary=hero.querySelector('.btn.secondary');if(secondary&&!secondary.dataset.launchv2){const n=secondary.cloneNode(true);n.dataset.launchv2='1';n.removeAttribute('onclick');n.textContent='查看 Free／Complete 差異';n.addEventListener('click',e=>{e.preventDefault();d.getElementById('plans')?.scrollIntoView({behavior:'smooth',block:'start'})});secondary.replaceWith(n)}}const nav=d.querySelector('.top nav .links');if(nav&&!nav.dataset.launchv2){nav.dataset.launchv2='1';nav.innerHTML='<a href="#" data-n="home">首頁</a><a href="#" data-n="free">免費 3 題</a><a href="#" data-n="complete">AI Complete</a><a href="#" data-n="mock">Weekly Mock</a><a href="#" data-n="history">歷屆題</a><a href="#" data-n="analysis">弱點分析</a>';nav.querySelectorAll('[data-n]').forEach(a=>a.onclick=e=>{e.preventDefault();const k=a.dataset.n;if(k==='home')hero?.scrollIntoView({behavior:'smooth'});else if(k==='free')dispatch('ltu:start-practice',{mode:'core'});else if(k==='complete')d.getElementById('plans')?.scrollIntoView({behavior:'smooth',block:'start'});else d.getElementById(k==='mock'?'weekly':k)?.scrollIntoView({behavior:'smooth',block:'start'})})}['examguide','dashboard','daily','wrongbook','notes','global','admin'].forEach(id=>{const el=d.getElementById(id);if(el)el.style.display='none'});const plans=d.getElementById('plans');if(plans){plans.style.display='block';plans.classList.remove('pcHide','v19Locked')}d.getElementById('pcoreMembership')?.remove();d.getElementById('membershipCompareV18')?.remove();d.getElementById('upgradeV15')?.remove();const acc=d.getElementById('accountBtn');if(acc)acc.textContent=acc.textContent.includes('Complete')?'AI Complete 帳號':'登入／帳號'}
window.addEventListener('ltu:start-practice',async e=>{if(replaying)return;const x=await authMe();if(!x?.authenticated)savePending(e.detail||{mode:'core'})});
window.addEventListener('ltu:auth-changed',async()=>{const x=await authMe();if(!x?.authenticated)return;const p=takePending();if(!p)return;setTimeout(()=>{replaying=true;dispatch('ltu:start-practice',p);setTimeout(()=>{replaying=false},500)},350)});
window.addEventListener('ltu:goto',e=>{const d=deepest(),id=e.detail?.id||e.detail;if(!d||!id)return;if(id==='notes'||id==='notebook'){dispatch('ltu:open-notebook');return}if(id==='account'){dispatch('ltu:open-auth');return}d.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})});
window.addEventListener('beforeunload',e=>{const d=deepest();if(practiceInProgress(d)||mockInProgress(d)){e.preventDefault();e.returnValue=''}});
setInterval(()=>cleanup(deepest()),700);setTimeout(()=>cleanup(deepest()),200);window.addEventListener('ltu:product-refresh',()=>setTimeout(()=>cleanup(deepest()),250));
})();