(function(){'use strict';
const labels={all:'全部',vocabulary:'單字',phrase:'片語',grammar:'文法',sentence_pattern:'句型',mistake:'錯因',weakness:'弱點',strategy:'策略'};
const zhMap={'义':'義','语':'語','与':'與','词':'詞','则':'則','频':'頻','结':'結','错':'錯','为':'為','么':'麼','选':'選','种':'種','复':'複','阅':'閱','听':'聽','间':'間','验':'驗','证':'證','记':'記','账':'帳','个':'個','读':'讀','类':'類','题':'題','这':'這','会':'會','暂':'暫','级':'級','后':'後','长':'長','体':'體','别':'別','发':'發','应':'應','总':'總','数':'數','归':'歸','续':'續','习':'習','线':'線','书':'書','张':'張'};
function tw(v){return String(v??'').replace(/[义语与词则频结错为么选种复阅听间验证记账个读类题这会暂级后长体别发应总数归续习线书张]/g,c=>zhMap[c]||c)}
let lastComplete=null,busy=false;
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<32;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
async function api(url,opts={}){try{const r=await fetch(url,{credentials:'include',...opts});return{ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}}catch{return{ok:false,status:0,data:null}}}
async function summary(){return(await api('/api/notebook/summary')).data}
async function list(cat='all'){return(await api('/api/notebook/list?category='+encodeURIComponent(cat))).data}
async function review(id,correct=true){return await api('/api/notebook/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,correct})})}
function styles(d){if(d.getElementById('nb2style'))return;const s=d.createElement('style');s.id='nb2style';s.textContent=`
#ltuNotebookCompact{position:relative;margin:34px 0;border:1px solid #e4dac1;background:#fffdf6;border-radius:28px;padding:30px 30px 30px 54px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif;color:#173957;box-shadow:0 18px 45px rgba(68,88,110,.10);overflow:hidden}
#ltuNotebookCompact:before{content:"";position:absolute;left:22px;top:0;bottom:0;width:3px;background:#d9e8f7;box-shadow:10px 0 0 #f1b7b7}
#ltuNotebookCompact:after{content:"";position:absolute;left:9px;top:28px;width:26px;height:calc(100% - 56px);background:radial-gradient(circle at 13px 8px,#719cc8 0 4px,#fff 4.5px 7px,transparent 7.5px) 0 0/26px 31px repeat-y;pointer-events:none}
.nb2head{display:flex;justify-content:space-between;gap:20px;align-items:center}.nb2head h2{margin:0;color:#123e6b;font-size:28px;letter-spacing:.02em}.nb2head p{margin:7px 0 0;color:#65788d;font-size:14px;line-height:1.7}.nbOpen{border:0;border-radius:999px;background:linear-gradient(135deg,#2d83f7,#176df3);color:#fff;padding:12px 20px;font-weight:900;cursor:pointer;white-space:nowrap;box-shadow:0 8px 20px rgba(23,109,243,.18)}
.nb2stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-top:20px}.nb2stat{background:#fffaf0;border:1px solid #eadfc5;border-radius:18px;padding:16px;min-height:78px;box-shadow:0 7px 18px rgba(70,90,110,.06)}.nb2stat b{display:block;font-size:26px;color:#176df3}.nb2stat span{font-size:12px;color:#71849a}
.nb2sample{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:22px}.nb2note{position:relative;min-height:155px;border:1px solid #e4d7b8;border-radius:18px;padding:22px 18px 18px 34px;font-size:14px;color:#566c82;line-height:1.7;background-color:#fff9df;background-image:repeating-linear-gradient(to bottom,transparent 0,transparent 29px,#d9e7f4 30px,#d9e7f4 31px);box-shadow:0 10px 22px rgba(94,83,58,.08);overflow:hidden}.nb2note:before{content:"";position:absolute;left:12px;top:12px;bottom:12px;width:8px;background:radial-gradient(circle,#789bc1 0 3px,#fff 3.5px 5px,transparent 5.5px) center top/8px 24px repeat-y}.nb2note b{display:block;color:#174d80;margin-bottom:11px;font-size:16px}.nb2note small{display:inline-block;margin-bottom:9px;padding:4px 8px;border-radius:999px;background:#eef6ff;color:#2c6fae;font-size:10px;font-weight:900}.nb2note:nth-child(2n){transform:rotate(.25deg)}.nb2note:nth-child(3n){transform:rotate(-.2deg)}
.nb2modal{position:fixed;inset:0;background:#071e35aa;z-index:1000000;display:none;place-items:center;padding:18px}.nb2modal.show{display:grid}.nb2box{width:min(960px,100%);max-height:93vh;overflow:auto;background:#fffdf7;border-radius:28px;padding:28px;box-shadow:0 35px 90px #00182f55;border:1px solid #eadfc5}.nb2top{display:flex;justify-content:space-between;gap:14px;align-items:center}.nb2top h2{margin:0;color:#0d2f57}.nb2close{border:0;background:#eef3f8;border-radius:50%;width:38px;height:38px;font-size:20px;cursor:pointer}.nb2filters{display:flex;gap:7px;flex-wrap:wrap;margin:18px 0}.nb2filters button{border:1px solid #dce7f2;background:#fff;color:#47627c;border-radius:999px;padding:8px 12px;font-size:11px;cursor:pointer}.nb2filters button.on{background:#176df3;color:#fff;border-color:#176df3}.nb2list{display:grid;gap:13px}.nb2item{border:1px solid #e6dcc4;border-radius:18px;padding:18px 18px 18px 30px;background-color:#fffaf0;background-image:repeating-linear-gradient(to bottom,transparent 0,transparent 31px,#e4edf6 32px,#e4edf6 33px);position:relative}.nb2item:before{content:"";position:absolute;left:10px;top:12px;bottom:12px;width:7px;background:radial-gradient(circle,#789bc1 0 3px,#fff 3.5px 5px,transparent 5.5px) center top/7px 23px repeat-y}.nb2itemtop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.nb2cat{font-size:10px;background:#eef5ff;color:#176df3;border-radius:999px;padding:5px 8px}.nb2item p{font-size:13px;color:#566f87;line-height:1.75;margin:12px 0}.nb2foot{font-size:11px;color:#8998a7;display:flex;justify-content:space-between;gap:10px;align-items:center}.nb2review{border:0;border-radius:999px;background:#eef5ff;color:#176df3;padding:7px 10px;font-size:10px;font-weight:850;cursor:pointer}.nb2empty{text-align:center;color:#7c8da0;padding:36px}.nb2due{background:#fff0b8;border-radius:12px;padding:9px 11px;color:#765c1d;font-size:11px;margin-top:9px}
@media(max-width:980px){.nb2sample{grid-template-columns:repeat(2,1fr)}.nb2stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){#ltuNotebookCompact{padding:24px 16px 24px 42px}.nb2head{align-items:flex-start;flex-direction:column}.nb2head h2{font-size:24px}.nb2sample,.nb2stats{grid-template-columns:1fr}.nb2note{min-height:135px}.nb2foot{align-items:flex-start;flex-direction:column}}
`;d.head.appendChild(s)}
function sample(){const items=[['Vocabulary','單字','字義、近義字、語境。'],['Phrase','片語','固定搭配與介系詞。'],['Grammar','文法','造成失分的文法規則。'],['Sentence Pattern','句型','高頻句型與句構。'],['Mistake','錯因整理','為什麼會選錯。'],['Weakness','弱點分析','哪種能力反覆出錯。'],['Strategy','解題策略','閱讀／聽力判斷線索。'],['Review','間隔複習','3／7／21／30 天再驗證。']];return`<div class="nb2sample">${items.map(([en,zh,txt])=>`<div class="nb2note"><small>${en}</small><b>${zh}</b>${txt}</div>`).join('')}</div>`}
function ensureModal(d){let m=d.getElementById('nb2modal');if(m)return m;m=d.createElement('div');m.id='nb2modal';m.className='nb2modal';m.innerHTML='<div class="nb2box"><div class="nb2top"><div><h2>我的 AI 筆記</h2><div style="font-size:11px;color:#7b8da0;margin-top:4px">AI Complete｜帳號同步</div></div><button class="nb2close">×</button></div><div id="nb2body"></div></div>';d.body.appendChild(m);m.querySelector('.nb2close').onclick=()=>m.classList.remove('show');m.onclick=e=>{if(e.target===m)m.classList.remove('show')};return m}
async function open(d,isComplete){const m=ensureModal(d),body=m.querySelector('#nb2body');m.classList.add('show');if(!isComplete){body.innerHTML='<div class="nb2empty">免費會員可以預覽 AI 筆記結構；個人筆記與複習排程屬於 AI Complete。</div>'+sample();return}body.innerHTML='<div class="nb2empty">正在讀取你的 AI 筆記…</div>';await renderList(d,body,'all')}
async function renderList(d,body,cat){const x=await list(cat);if(!x?.items){body.innerHTML='<div class="nb2empty">暫時無法讀取筆記，請重新登入後再試。</div>';return}body.innerHTML=`<div class="nb2filters">${Object.entries(labels).map(([k,v])=>`<button data-cat="${k}" class="${k===cat?'on':''}">${v}</button>`).join('')}</div><div class="nb2list">${x.items.length?x.items.map((n,i)=>`<article class="nb2item"><div class="nb2itemtop"><strong>${String(i+1).padStart(3,'0')} · ${tw(n.title)}</strong><span class="nb2cat">${labels[n.category]||tw(n.category)}</span></div><p>${tw(n.content)}</p><div class="nb2foot"><span>題目 ${n.question_id} · 掌握度 ${Number(n.mastery_level||0)}/4${n.review_at?' · 下次 '+new Date(n.review_at).toLocaleDateString('zh-TW'):''}</span><button class="nb2review" data-id="${n.id}">這個我會了 ✓</button></div>${n.review_at&&new Date(n.review_at)<=new Date()?'<div class="nb2due">今天已到複習時間，建議先確認自己是否還記得這個觀念。</div>':''}</article>`).join(''):'<div class="nb2empty">這個分類還沒有筆記。完成錯題後會自動整理。</div>'}</div>`;body.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>renderList(d,body,b.dataset.cat));body.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='更新中…';const r=await review(Number(b.dataset.id),true);if(!r.ok){b.disabled=false;b.textContent='重試';return}await renderList(d,body,cat);window.dispatchEvent(new CustomEvent('ltu:notebook-updated'))})}
async function mount(force=false){if(busy)return;busy=true;try{const d=deepest();if(!d?.body)return;styles(d);const x=await summary(),isComplete=!!x?.complete;let sec=d.getElementById('ltuNotebookCompact');if(!sec){sec=d.createElement('section');sec.id='ltuNotebookCompact'}const target=d.getElementById('pcoreMembership')||d.getElementById('accountV16')||d.querySelector('main');if(target&&sec.parentNode!==target.parentNode)target.insertAdjacentElement('afterend',sec);else if(target&&target.nextElementSibling!==sec)target.insertAdjacentElement('afterend',sec);if(force||lastComplete!==isComplete||!sec.dataset.ready){const c=x?.counts||{};sec.innerHTML=`<div class="nb2head"><div><h2>${isComplete?'我的 AI 筆記':'AI 筆記預覽'}</h2><p>${isComplete?'錯題會自動整理成個人重點，並安排下一次複習。':'Free 可體驗每日 3 題；升級後才會建立個人 AI 筆記與間隔複習。'}</p></div><button class="nbOpen">${isComplete?'查看我的筆記':'查看筆記範例'}</button></div>${isComplete?`<div class="nb2stats"><div class="nb2stat"><b>${c.total||0}</b><span>全部筆記</span></div><div class="nb2stat"><b>${c.grammar||0}</b><span>文法</span></div><div class="nb2stat"><b>${(c.vocabulary||0)+(c.phrase||0)}</b><span>單字／片語</span></div><div class="nb2stat"><b>${c.weakness||0}</b><span>弱點</span></div><div class="nb2stat"><b>${c.due||0}</b><span>待複習</span></div></div>`:sample()}`;sec.querySelector('.nbOpen').onclick=()=>open(d,isComplete);sec.dataset.ready='1';lastComplete=isComplete}sec.classList.remove('pcHide')}finally{busy=false}}
window.addEventListener('ltu:open-notebook',()=>{const d=deepest(),sec=d?.getElementById('ltuNotebookCompact');if(sec?.querySelector('.nbOpen'))sec.querySelector('.nbOpen').click();else mount(true).then(()=>deepest()?.getElementById('ltuNotebookCompact')?.querySelector('.nbOpen')?.click())});window.addEventListener('ltu:notebook-updated',()=>setTimeout(()=>mount(true),250));window.addEventListener('ltu:product-refresh',()=>setTimeout(()=>mount(true),450));setTimeout(()=>mount(true),500);setInterval(()=>mount(false),8000);window.LTUNotebookV2={mount,open};
})();
