(function(){
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<32;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
async function getSummary(){try{const r=await fetch('/api/notebook/summary',{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
async function getList(category='all'){try{const r=await fetch('/api/notebook/list?category='+encodeURIComponent(category),{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
async function review(id,correct=true){try{const r=await fetch('/api/notebook/review',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,correct})});return r.ok?await r.json():null}catch{return null}}
function styles(d){if(d.getElementById('ltuNotebookStyle'))return;const s=d.createElement('style');s.id='ltuNotebookStyle';s.textContent=`
#ltuNotebookCompact{margin:18px 0;border:1px solid #e3ebf5;background:linear-gradient(180deg,#fff,#f8fbff);border-radius:24px;padding:18px 20px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif;color:#173957}.nbHead{display:flex;justify-content:space-between;gap:16px;align-items:center}.nbHead h3{margin:0;font-size:20px}.nbHead p{margin:4px 0 0;color:#72849a;font-size:12px}.nbStats{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:14px}.nbStat{background:#fff;border:1px solid #e5edf6;border-radius:15px;padding:10px}.nbStat b{display:block;font-size:19px;color:#176df3}.nbStat span{font-size:10px;color:#71849a}.nbOpen{border:0;border-radius:999px;background:#176df3;color:#fff;padding:10px 15px;font-weight:800;cursor:pointer}.nbSample{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.nbSample span{font-size:10px;padding:6px 9px;border-radius:999px;background:#eef5ff;color:#2f5f91}.nbModal{position:fixed;inset:0;background:#071e35aa;z-index:100000;display:none;place-items:center;padding:18px}.nbModal.show{display:grid}.nbBox{width:min(920px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:28px;padding:24px;box-shadow:0 35px 90px #00182f55}.nbTop{display:flex;justify-content:space-between;gap:15px;align-items:center}.nbTop h2{margin:0;color:#0d2f57}.nbClose{border:0;background:#eef3f8;border-radius:50%;width:38px;height:38px;font-size:20px;cursor:pointer}.nbFilters{display:flex;gap:7px;flex-wrap:wrap;margin:16px 0}.nbFilters button{border:1px solid #dce7f2;background:#fff;color:#47627c;border-radius:999px;padding:7px 10px;font-size:11px;cursor:pointer}.nbFilters button.active{background:#176df3;color:#fff;border-color:#176df3}.nbList{display:grid;gap:10px}.nbItem{border:1px solid #e4edf6;border-radius:18px;padding:14px}.nbItemTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.nbItem strong{color:#1c456d}.nbCat{font-size:10px;background:#eef5ff;color:#176df3;border-radius:999px;padding:4px 7px}.nbItem p{font-size:12px;color:#60758b;line-height:1.6;margin:8px 0}.nbFoot{font-size:10px;color:#92a0ad;display:flex;justify-content:space-between;gap:10px;align-items:center}.nbReview{border:0;border-radius:999px;background:#eef5ff;color:#176df3;padding:6px 9px;font-size:10px;font-weight:800;cursor:pointer}.nbEmpty{text-align:center;color:#7c8da0;padding:40px}.nbExampleGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:15px}.nbExample{background:#f7f9fc;border-radius:16px;padding:13px}.nbExample b{font-size:12px;color:#28527d}.nbExample p{font-size:11px;line-height:1.6;color:#71849a;margin:5px 0 0}@media(max-width:760px){.nbStats{grid-template-columns:repeat(2,1fr)}.nbExampleGrid{grid-template-columns:1fr}.nbHead{align-items:flex-start}.nbOpen{white-space:nowrap}}
`;d.head.appendChild(s)}
const labels={all:'全部',vocabulary:'單字',phrase:'片語',grammar:'文法',sentence_pattern:'句型',mistake:'錯因',weakness:'弱點',strategy:'策略'};
function ensureModal(d){let m=d.getElementById('ltuNotebookModal');if(m)return m;m=d.createElement('div');m.id='ltuNotebookModal';m.className='nbModal';m.innerHTML='<div class="nbBox"><div class="nbTop"><div><h2>我的 AI 筆記</h2><div style="font-size:11px;color:#7b8da0;margin-top:4px">LTU 國際學術中心｜完整會員專屬</div></div><button class="nbClose">×</button></div><div id="nbModalBody"></div></div>';d.body.appendChild(m);m.querySelector('.nbClose').onclick=()=>m.classList.remove('show');m.onclick=e=>{if(e.target===m)m.classList.remove('show')};return m}
function exampleHTML(){return `<div class="nbExampleGrid"><div class="nbExample"><b>01 Vocabulary｜單字整理</b><p>記錄不熟悉的字義、近義字與題目中的語境。</p></div><div class="nbExample"><b>02 Phrase｜片語搭配</b><p>整理固定搭配、介系詞與容易混淆的片語。</p></div><div class="nbExample"><b>03 Grammar｜文法重點</b><p>記錄真正造成錯誤的文法規則與判斷線索。</p></div><div class="nbExample"><b>04 Sentence Pattern｜句型</b><p>整理常考句型，例如 ask + O + to V。</p></div><div class="nbExample"><b>05 錯因</b><p>記錄你為什麼會選錯，而不只寫正確答案。</p></div><div class="nbExample"><b>06 弱點提示</b><p>AI 累積哪些能力反覆出錯，安排後續練習。</p></div><div class="nbExample"><b>07 下次複習</b><p>錯題進入間隔複習，3、7、21、30 天逐步驗證。</p></div></div>`}
async function openNotebook(d,complete){const m=ensureModal(d),body=m.querySelector('#nbModalBody');m.classList.add('show');if(!complete){body.innerHTML='<p style="color:#667b91;line-height:1.7">免費會員可查看 AI 筆記範例；個人 AI 筆記、弱點追蹤與間隔複習為完整會員功能。</p>'+exampleHTML();return}body.innerHTML='<div class="nbEmpty">正在讀取你的 AI 筆記…</div>';await renderList(d,body,'all')}
async function renderList(d,body,cat){const data=await getList(cat);if(!data?.items){body.innerHTML='<div class="nbEmpty">目前還沒有筆記。完成練習後，錯題會自動整理進來。</div>';return}body.innerHTML=`<div class="nbFilters">${Object.entries(labels).map(([k,v])=>`<button data-cat="${k}" class="${k===cat?'active':''}">${v}</button>`).join('')}</div><div class="nbList">${data.items.length?data.items.map((n,i)=>`<div class="nbItem"><div class="nbItemTop"><strong>${String(i+1).padStart(3,'0')} · ${n.title}</strong><span class="nbCat">${labels[n.category]||n.category}</span></div><p>${n.content}</p><div class="nbFoot"><span>題目 ${n.question_id} · 掌握度 ${Number(n.mastery_level||0)}/4${n.review_at?' · 下次複習 '+new Date(n.review_at).toLocaleDateString('zh-TW'):''}</span><button class="nbReview" data-id="${n.id}">這個我會了 ✓</button></div></div>`).join(''):'<div class="nbEmpty">這個分類目前沒有筆記。</div>'}</div>`;body.querySelectorAll('.nbFilters button').forEach(b=>b.onclick=()=>renderList(d,body,b.dataset.cat));body.querySelectorAll('.nbReview').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='更新中…';await review(Number(b.dataset.id),true);await renderList(d,body,cat);window.dispatchEvent(new CustomEvent('ltu:notebook-updated'))})}
async function build(){const d=deepest();if(!d||!d.body)return;styles(d);const plans=d.querySelector('.v3Plans');if(!plans||d.getElementById('ltuNotebookCompact'))return;const summary=await getSummary(),complete=!!summary?.complete;const c=summary?.counts||{};const box=d.createElement('section');box.id='ltuNotebookCompact';box.innerHTML=`<div class="nbHead"><div><h3>${complete?'我的 AI 筆記':'AI 筆記範例'}</h3><p>${complete?'錯題會自動整理，並安排下一次複習。':'免費會員只能查看範例；完整會員才建立個人 AI 筆記。'}</p></div><button class="nbOpen">${complete?'查看我的 AI 筆記':'查看筆記範例'}</button></div>${complete?`<div class="nbStats"><div class="nbStat"><b>${c.total||0}</b><span>AI 筆記</span></div><div class="nbStat"><b>${c.grammar||0}</b><span>文法重點</span></div><div class="nbStat"><b>${(c.vocabulary||0)+(c.phrase||0)}</b><span>單字／片語</span></div><div class="nbStat"><b>${c.weakness||0}</b><span>弱點提示</span></div><div class="nbStat"><b>${c.due||0}</b><span>待複習</span></div></div>`:`<div class="nbSample"><span>01 單字</span><span>02 片語</span><span>03 文法</span><span>04 句型</span><span>05 錯因</span><span>06 弱點</span><span>07 下次複習</span></div>`};plans.insertAdjacentElement('afterend',box);box.querySelector('.nbOpen').onclick=()=>openNotebook(d,complete);const old=d.querySelector('.v3Note');if(old)old.style.display='none';const menuBtn=[...d.querySelectorAll('#v3Menu button')].find(x=>(x.textContent||'').includes('AI 筆記'));if(menuBtn){menuBtn.onclick=e=>{e.preventDefault();e.stopPropagation();openNotebook(d,complete)}}}
async function refresh(){const d=deepest(),old=d.getElementById('ltuNotebookCompact');if(old)old.remove();await build()}
setInterval(build,800);window.addEventListener('ltu:notebook-updated',()=>setTimeout(refresh,250));
})();