(function(){
const LOCAL='ltuCapSeenV1';
function localSeen(){try{return JSON.parse(localStorage.getItem(LOCAL)||'[]')}catch{return[]}}
function addLocal(id){const a=localSeen();if(!a.includes(id))a.push(id);localStorage.setItem(LOCAL,JSON.stringify(a.slice(-5000)))}
async function profile(){try{const r=await fetch('/api/practice/profile',{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
async function saveAnswer(q,selected,correct){try{await fetch('/api/practice/answer',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,type:q.type,competency:q.meta?.competency||q.type,grammarFocus:q.meta?.grammarFocus||'',selectedIndex:selected,correct})})}catch{}}
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<32;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
function ensure(d){let m=d.getElementById('ltuPracticeModal');if(m)return m;const s=d.createElement('style');s.textContent='#ltuPracticeModal{position:fixed;inset:0;background:#061b31a8;z-index:99999;display:none;place-items:center;padding:18px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif}#ltuPracticeModal.show{display:grid}.lp2{width:min(860px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:28px;padding:26px;box-shadow:0 30px 90px #00152b44}.lp2top{display:flex;justify-content:space-between;gap:12px;align-items:center}.lp2 h2{margin:0;color:#0d2f57}.lp2close{border:0;background:#eef3f8;border-radius:50%;width:38px;height:38px;font-size:20px}.lp2stem{white-space:pre-line;font-size:18px;line-height:1.75;color:#203b57;margin:16px 0}.lp2opts{display:grid;gap:10px}.lp2opt{border:1px solid #dce7f1;background:#fff;border-radius:16px;padding:13px 15px;text-align:left;font-size:15px;cursor:pointer}.lp2opt.good{background:#eef9f2;border-color:#56a678}.lp2opt.bad{background:#fff2f2;border-color:#d77676}.lp2ex{display:none;margin-top:15px;padding:16px;border-radius:18px;background:#f6f9fc;color:#455f78;line-height:1.7}.lp2ex.show{display:block}.lp2next{display:none;margin-top:14px;border:0;border-radius:999px;background:#176df3;color:#fff;padding:11px 18px;font-weight:800}.lp2next.show{display:inline-block}.lp2meta{font-size:12px;color:#72849a}.lp2tag{display:inline-block;background:#eef5ff;color:#176df3;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800}.lp2sum{text-align:center;padding:24px}.lp2sum strong{font-size:34px;color:#176df3}.lp2weak{margin-top:14px;padding:14px;background:#eef7ff;border-radius:16px;color:#345a7d;font-size:13px}';d.head.appendChild(s);m=d.createElement('div');m.id='ltuPracticeModal';m.innerHTML='<div class="lp2"><div id="lp2body"></div></div>';d.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.classList.remove('show')};return m}
function weakTypes(p){if(!p?.complete||!Array.isArray(p.weakness))return[];return p.weakness.filter(x=>Number(x.weight)>0.4).slice(0,3).map(x=>String(x.skill))}
function mapSkillToType(skill){const s=String(skill).toLowerCase();if(s.includes('tense')||s.includes('comparison')||s.includes('grammar'))return'grammar';if(s.includes('listening'))return'listening';if(s.includes('main'))return'mainIdea';if(s.includes('infer'))return'inference';if(s.includes('reference'))return'reference';if(s.includes('detail'))return'detail';if(s.includes('collocation'))return'collocation';if(s.includes('sentence'))return'sentencePattern';if(s.includes('connect'))return'connectors';if(s.includes('word'))return'vocabulary';return''}
async function start(){const d=deepest(),eng=window.LTUQuestionEngine;if(!eng)return alert('題庫引擎載入中，請稍後再試。');const p=await profile();let meData=null;try{const r=await fetch('/api/auth/me',{credentials:'include'});meData=r.ok?await r.json():null}catch{}const complete=!!p?.complete||!!(meData?.authenticated&&meData?.user?.membershipPlan==='complete');const count=complete?10:3;const serverSeen=complete&&Array.isArray(p?.seen)?p.seen:[];const seen=[...new Set([...serverSeen,...localSeen()])];let batch=[];if(complete){const wt=weakTypes(p).map(mapSkillToType).filter(Boolean);const target=Math.min(6,count);if(wt.length){for(let i=0;i<target;i++){const type=wt[i%wt.length];const q=eng.getBatch({count:1,seen:[...seen,...batch.map(x=>x.id)],types:[type]})[0];if(q)batch.push(q)}}}const rest=eng.getBatch({count:count-batch.length,seen:[...seen,...batch.map(x=>x.id)]});batch=batch.concat(rest);const m=ensure(d),body=m.querySelector('#lp2body');m.classList.add('show');let idx=0,score=0,mistakes=[];
function render(){if(idx>=batch.length){const top=p?.weakness?.[0];body.innerHTML=`<div class="lp2top"><div><h2>今日練習完成</h2><div class="lp2meta">LTU 國際學術中心｜CAP English AI</div></div><button class="lp2close">×</button></div><div class="lp2sum"><strong>${score} / ${batch.length}</strong><p>${complete?'本次作答已寫入你的 AI 長期學習記憶；換裝置登入後仍可延續。':'免費會員每日 3 題體驗完成；免費會員不建立 AI 長期弱點記憶。'}</p>${complete?`<div class="lp2weak">目前優先弱點：<b>${top?.skill||'尚在累積資料'}</b>　｜　伺服器已避開近期做過的 ${serverSeen.length} 題</div>`:''}</div>`;body.querySelector('.lp2close').onclick=()=>m.classList.remove('show');return}const q=batch[idx];body.innerHTML=`<div class="lp2top"><div><h2>${complete?'AI Complete 個人練習':'免費會員每日 3 題'}</h2><div class="lp2meta">第 ${idx+1} / ${batch.length} 題 · ${q.id}</div></div><button class="lp2close">×</button></div><span class="lp2tag">${q.type}</span><div class="lp2stem">${q.stem}</div>${q.meta?.audioText?'<button id="lp2audio" class="lp2next show">▶ 播放聽力</button>':''}<div class="lp2opts"></div><div class="lp2ex"></div><button class="lp2next" id="lp2next">下一題 →</button>`;body.querySelector('.lp2close').onclick=()=>m.classList.remove('show');if(q.meta?.audioText)body.querySelector('#lp2audio').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.meta.audioText);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)};const opts=body.querySelector('.lp2opts');let answered=false;q.options.forEach((op,i)=>{const b=d.createElement('button');b.className='lp2opt';b.textContent=`${String.fromCharCode(65+i)}. ${op}`;b.onclick=async()=>{if(answered)return;answered=true;const ok=i===q.answer;addLocal(q.id);if(ok){score++;b.classList.add('good')}else{mistakes.push(q);b.classList.add('bad');opts.children[q.answer]?.classList.add('good')}if(complete)saveAnswer(q,i,ok);const ex=body.querySelector('.lp2ex');ex.innerHTML=`<b>${ok?'答對了':'AI 錯因提醒'}</b><br>${q.explanation}<br><small>能力標籤：${q.meta?.competency||q.type}${q.meta?.grammarFocus?' · '+q.meta.grammarFocus:''}</small>`;ex.classList.add('show');body.querySelector('#lp2next').classList.add('show')};opts.appendChild(b)});body.querySelector('#lp2next').onclick=()=>{idx++;render()}}
render()}
function bind(){const d=deepest();if(!d)return;['v3FreeStart','v3Start'].forEach(id=>{const el=d.getElementById(id);if(el&&!el.dataset.practiceV2){el.dataset.practiceV2='1';el.dataset.practiceBound='1';el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();start()},true)}})}
setInterval(bind,500);
})();