(function(){
const KEY='ltuCapSeenV1';
function seen(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function addSeen(id){const a=seen();if(!a.includes(id))a.push(id);localStorage.setItem(KEY,JSON.stringify(a.slice(-5000)))}
async function me(){try{const r=await fetch('/api/auth/me',{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
function styles(d){if(d.getElementById('ltuPracticeStyle'))return;const s=d.createElement('style');s.id='ltuPracticeStyle';s.textContent=`
#ltuPracticeModal{position:fixed;inset:0;background:rgba(4,20,39,.58);z-index:99999;display:none;place-items:center;padding:18px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC","Segoe UI",sans-serif}#ltuPracticeModal.show{display:grid}.lpBox{width:min(860px,100%);max-height:92vh;overflow:auto;background:white;border-radius:28px;box-shadow:0 30px 90px rgba(0,0,0,.22);padding:26px}.lpTop{display:flex;align-items:center;justify-content:space-between;gap:14px}.lpTop h2{margin:0;color:#0d2f57;font-size:26px}.lpMeta{font-size:12px;color:#72849a}.lpClose{border:0;background:#eef3f8;border-radius:999px;width:38px;height:38px;font-size:20px;cursor:pointer}.lpProgress{height:8px;background:#edf2f7;border-radius:999px;margin:18px 0;overflow:hidden}.lpProgress i{display:block;height:100%;background:#176df3;width:0}.lpType{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef5ff;color:#176df3;font-weight:800;font-size:11px}.lpStem{white-space:pre-line;font-size:18px;line-height:1.75;color:#203b57;margin:16px 0}.lpAudio{border:0;border-radius:999px;padding:10px 15px;background:#0d2f57;color:white;font-weight:800;cursor:pointer;margin-bottom:10px}.lpOpts{display:grid;gap:10px}.lpOpt{border:1px solid #dce7f1;background:#fff;border-radius:16px;padding:13px 15px;text-align:left;font-size:15px;color:#29445e;cursor:pointer}.lpOpt:hover{border-color:#8ebaf2;background:#f8fbff}.lpOpt.good{border-color:#56a678;background:#eef9f2}.lpOpt.bad{border-color:#d77676;background:#fff2f2}.lpExplain{display:none;margin-top:16px;padding:16px;border-radius:18px;background:#f7f9fc;color:#455f78;line-height:1.7}.lpExplain.show{display:block}.lpNext{display:none;margin-top:14px;border:0;border-radius:999px;padding:11px 18px;background:#176df3;color:white;font-weight:850;cursor:pointer}.lpNext.show{display:inline-flex}.lpSummary{text-align:center;padding:32px 10px}.lpSummary h3{font-size:28px;color:#0d2f57;margin:0 0 8px}.lpSummary p{color:#64788e;line-height:1.7}.lpStatGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.lpStat{background:#f5f8fc;border-radius:18px;padding:16px}.lpStat b{display:block;font-size:24px;color:#176df3}.lpStat span{font-size:11px;color:#77899d}.lpPool{margin-top:14px;background:#eef7ff;border-radius:15px;padding:12px 14px;color:#345a7d;font-size:12px}
@media(max-width:620px){.lpBox{padding:18px;border-radius:20px}.lpStatGrid{grid-template-columns:1fr}.lpStem{font-size:16px}}
`;d.head.appendChild(s)}
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<32;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
function ensure(d){styles(d);if(d.getElementById('ltuPracticeModal'))return d.getElementById('ltuPracticeModal');const m=d.createElement('div');m.id='ltuPracticeModal';m.innerHTML='<div class="lpBox"><div id="lpBody"></div></div>';d.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});return m}
async function start(planHint){const d=deepest();const eng=window.LTUQuestionEngine;if(!eng)return alert('題庫引擎載入中，請稍後再試。');const profile=await me();const isComplete=profile?.authenticated&&profile?.user?.membershipPlan==='complete';const limit=isComplete?10:3;const batch=eng.getBatch({count:limit,seen:seen()});const m=ensure(d),body=m.querySelector('#lpBody');m.classList.add('show');let idx=0,score=0,answered=false;const mistakes=[];
function render(){if(idx>=batch.length){body.innerHTML=`<div class="lpTop"><div><h2>今日練習完成</h2><div class="lpMeta">LTU 國際學術中心｜CAP English AI</div></div><button class="lpClose">×</button></div><div class="lpSummary"><h3>${score} / ${batch.length}</h3><p>${isComplete?'AI Complete 會把今天的錯題作為後續弱點練習依據。':'免費會員每日 3 題體驗完成。完整會員可每日 10 題並啟用 AI 記憶出題。'}</p><div class="lpStatGrid"><div class="lpStat"><b>${batch.length}</b><span>今日題數</span></div><div class="lpStat"><b>${mistakes.length}</b><span>需要再練</span></div><div class="lpStat"><b>${seen().length}</b><span>本裝置已完成不同題目</span></div></div><div class="lpPool">目前原創變式題引擎可產生 <b>${eng.count().toLocaleString()}+</b> 個可識別題目實例，並優先避開本裝置近期做過的題目。</div></div>`;body.querySelector('.lpClose').onclick=()=>m.classList.remove('show');return}
 const q=batch[idx];answered=false;body.innerHTML=`<div class="lpTop"><div><h2>${isComplete?'AI Complete 個人練習':'免費會員每日 3 題'}</h2><div class="lpMeta">第 ${idx+1} / ${batch.length} 題 · ${q.id}</div></div><button class="lpClose">×</button></div><div class="lpProgress"><i style="width:${((idx)/batch.length)*100}%"></i></div><span class="lpType">${q.type}</span><div class="lpStem">${q.stem}</div>${q.meta.audioText?'<button class="lpAudio">▶ 播放聽力</button>':''}<div class="lpOpts"></div><div class="lpExplain"></div><button class="lpNext">下一題 →</button>`;
 body.querySelector('.lpClose').onclick=()=>m.classList.remove('show');if(q.meta.audioText){body.querySelector('.lpAudio').onclick=()=>{try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.meta.audioText);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)}catch{}}}
 const opts=body.querySelector('.lpOpts');q.options.forEach((op,i)=>{const b=d.createElement('button');b.className='lpOpt';b.textContent=`${String.fromCharCode(65+i)}. ${op}`;b.onclick=()=>{if(answered)return;answered=true;addSeen(q.id);const correct=i===q.answer;if(correct){score++;b.classList.add('good')}else{b.classList.add('bad');mistakes.push(q);opts.children[q.answer]?.classList.add('good')}const ex=body.querySelector('.lpExplain');ex.innerHTML=`<b>${correct?'答對了':'這題的重點'}</b><br>${q.explanation}<br><small>能力標籤：${q.meta.competency||q.type}${q.meta.grammarFocus?' · '+q.meta.grammarFocus:''}</small>`;ex.classList.add('show');body.querySelector('.lpNext').classList.add('show')};opts.appendChild(b)});body.querySelector('.lpNext').onclick=()=>{idx++;render()};}
render()}
function bind(){const d=deepest();if(!d)return;['v3FreeStart','v3Start'].forEach(id=>{const el=d.getElementById(id);if(el&&!el.dataset.practiceBound){el.dataset.practiceBound='1';el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();start('free')},true)}});const cb=d.getElementById('v3CompleteBtn');if(cb&&!cb.dataset.practiceInfo){cb.dataset.practiceInfo='1'} }
setInterval(bind,700);
})();