(function(){'use strict';
const KEY='capStudyGoalV1';
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<20;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'})}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function ensureState(){const s=load(),t=today();if(s.day!==t)return{day:t,goal:Number(s.goal)||10,seconds:0,last:Date.now()};return{day:t,goal:Number(s.goal)||10,seconds:Number(s.seconds)||0,last:Number(s.last)||Date.now()}}
function style(d){if(d.getElementById('capGoalStyle'))return;const s=d.createElement('style');s.id='capGoalStyle';s.textContent=`#capStudyGoal{max-width:1120px;margin:14px auto 24px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif}.csgCard{border-radius:24px;padding:18px 20px;background:linear-gradient(135deg,#fff7df,#fff);border:1px solid #f0dda2;box-shadow:0 10px 28px rgba(138,102,20,.08)}.csgTop{display:flex;justify-content:space-between;gap:14px;align-items:center}.csgTitle{font-weight:950;color:#6d4d00;font-size:20px}.csgSub{font-size:11px;color:#8b7548;margin-top:4px}.csgChoices{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.csgChoices button{border:1px solid #ead89d;background:#fffaf0;color:#6f550e;border-radius:999px;padding:8px 12px;font-weight:850;cursor:pointer}.csgChoices button.on{background:#ffd968;border-color:#e2b935}.csgBar{height:13px;background:#f1ead8;border-radius:999px;overflow:hidden;margin-top:14px}.csgBar i{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#ffb52b,#ff7d27)}.csgFoot{display:flex;justify-content:space-between;gap:12px;font-size:11px;color:#7d6b47;margin-top:7px}@media(max-width:700px){.csgTop{align-items:flex-start;flex-direction:column}}`;d.head.appendChild(s)}
function mount(d){let state=ensureState(),s=d.getElementById('capStudyGoal');if(!s){s=d.createElement('section');s.id='capStudyGoal';const a=d.getElementById('capGamePolish')||d.getElementById('capGame')||d.getElementById('flowUxCard')||d.querySelector('main');if(a)a.insertAdjacentElement('afterend',s);else d.body.prepend(s)}const mins=Math.floor(state.seconds/60),pct=Math.min(100,Math.round(mins/Math.max(1,state.goal)*100));s.innerHTML=`<div class="csgCard"><div class="csgTop"><div><div class="csgTitle">今天想學多久？</div><div class="csgSub">先選一個做得到的目標。完成後會留下今天的學習紀錄。</div></div><strong>${mins} / ${state.goal} 分鐘</strong></div><div class="csgChoices">${[5,10,15,20].map(n=>`<button data-goal="${n}" class="${state.goal===n?'on':''}">${n} 分鐘</button>`).join('')}</div><div class="csgBar"><i style="width:${pct}%"></i></div><div class="csgFoot"><span>${pct>=100?'✓ 今日學習目標完成':'持續學習，離今天目標越來越近'}</span><span>${pct}%</span></div></div>`;s.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{state.goal=Number(b.dataset.goal);state.last=Date.now();save(state);mount(d)})}
function tick(){const d=deepest();if(!d?.body||document.hidden)return;let s=ensureState(),now=Date.now(),delta=Math.max(0,Math.min(30,Math.round((now-(s.last||now))/1000)));s.seconds+=delta;s.last=now;save(s);style(d);mount(d)}
setTimeout(()=>{const d=deepest();if(d?.body){style(d);mount(d)}},1000);setInterval(tick,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});window.LTUStudyGoal={refresh:()=>{const d=deepest();if(d?.body){style(d);mount(d)}}};
})();