(function(){'use strict';
function deepest(){try{let f=document.querySelector('iframe'),d=f?.contentDocument;if(!d)return document;for(let i=0;i<20;i++){const n=d.querySelector('iframe');if(!n||!n.contentDocument)break;d=n.contentDocument}return d}catch{return document}}
async function game(){try{const r=await fetch('/game-api',{credentials:'include'});return r.ok?await r.json():null}catch{return null}}
function tier(score){if(score>=520)return{n:'鑽石',icon:'💎',min:520,next:null};if(score>=340)return{n:'黃金',icon:'🏆',min:340,next:520};if(score>=180)return{n:'白銀',icon:'🥈',min:180,next:340};if(score>=70)return{n:'青銅',icon:'🥉',min:70,next:180};return{n:'新星',icon:'🌟',min:0,next:70}}
function scoreOf(x){const w=x.weekly||[],q=Number(w[0]?.value||0),c=Number(w[2]?.value||0),d=Number(w[1]?.value||0);return q*10+c*2+d*20}
function style(d){if(d.getElementById('capRankStyle'))return;const s=d.createElement('style');s.id='capRankStyle';s.textContent=`#capWeeklyRank{max-width:1120px;margin:14px auto 26px;font-family:-apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif}.cwrCard{border:1px solid #dbe7f4;border-radius:26px;background:linear-gradient(135deg,#f7fbff,#ffffff);padding:18px 20px;box-shadow:0 12px 30px rgba(30,93,155,.07)}.cwrTop{display:flex;justify-content:space-between;gap:16px;align-items:center}.cwrTitle{font-size:21px;font-weight:950;color:#173a5f}.cwrSub{font-size:11px;color:#708399;margin-top:4px;line-height:1.6}.cwrTier{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #dce8f4;border-radius:18px;padding:10px 14px}.cwrTier i{font-style:normal;font-size:30px}.cwrTier b{display:block;color:#173a5f}.cwrTier span{font-size:10px;color:#78899a}.cwrBar{height:14px;background:#e9eef4;border-radius:999px;overflow:hidden;margin-top:14px}.cwrBar i{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,#25b4ee,#176df3)}.cwrFoot{display:flex;justify-content:space-between;gap:10px;margin-top:7px;font-size:11px;color:#6f8092}.cwrMini{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.cwrMini div{background:#fff;border:1px solid #e2eaf2;border-radius:15px;padding:10px}.cwrMini b{display:block;color:#173a5f;font-size:17px}.cwrMini span{font-size:10px;color:#7a8a9a}@media(max-width:700px){.cwrTop{align-items:flex-start;flex-direction:column}.cwrTier{width:100%}.cwrMini{grid-template-columns:1fr}}`;d.head.appendChild(s)}
function mount(d,x){let s=d.getElementById('capWeeklyRank');if(!s){s=d.createElement('section');s.id='capWeeklyRank';const a=d.getElementById('capStudyGoal')||d.getElementById('capGame')||d.getElementById('flowUxCard')||d.querySelector('main');if(a)a.insertAdjacentElement('afterend',s);else d.body.prepend(s)}const sc=scoreOf(x),t=tier(sc),next=t.next,p=next?Math.max(0,Math.min(100,Math.round((sc-t.min)/(next-t.min)*100))):100;const w=x.weekly||[];s.innerHTML=`<div class="cwrCard"><div class="cwrTop"><div><div class="cwrTitle">本週段位</div><div class="cwrSub">依本週完成題數、答對題數與學習天數累積。這是自己的成長段位，不和其他學生公開排名。</div></div><div class="cwrTier"><i>${t.icon}</i><div><b>${t.n}</b><span>${next?`再 ${Math.max(0,next-sc)} 分升級`:'本週最高段位'}</span></div></div></div><div class="cwrBar"><i style="width:${p}%"></i></div><div class="cwrFoot"><span>本週成長分數 ${sc}</span><span>${p}%</span></div><div class="cwrMini"><div><b>${w[0]?.value||0}</b><span>本週完成題數</span></div><div><b>${w[2]?.value||0}</b><span>本週答對題數</span></div><div><b>${w[1]?.value||0}</b><span>本週學習天數</span></div></div></div>`}
async function render(){const d=deepest();if(!d?.body)return;style(d);const x=await game();if(!x?.ok){d.getElementById('capWeeklyRank')?.remove();return}mount(d,x)}
setTimeout(render,1400);setInterval(render,20000);['ltu:product-refresh','ltu:auth-changed'].forEach(n=>window.addEventListener(n,()=>setTimeout(render,500)));window.LTUWeeklyRank={refresh:render};
})();