import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
function ok(value,message){if(!value)throw new Error(`QA failed: ${message}`);console.log('✓',message)}
const read=p=>readFile(p,'utf8');
const browserFiles=['question-engine-v2.js','practice-ui-v4.js','notebook-ui-v2.js','auth-ui-v2.js','product-core-v1.js','launch-ui-v1.js','complete-preview-v1.js','complete-portal-v1.js','membership-sync-v1.js','remove-hero.js','cute-theme-v1.js'];
for(const file of browserFiles){const src=await read(file);new Function(src);ok(true,`${file} parses`)}
const hero=await readFile('public/cap-hero-cute.jpg');
ok(hero.length>1000&&hero[0]===0xff&&hero[1]===0xd8,'hero asset is a real JPEG, not a placeholder');
const cute=await read('cute-theme-v1.js');
ok(cute.includes('/cap-hero-cute.jpg'),'cute theme points to the verified hero asset');
const engineSrc=await read('question-engine-v2.js'),context={window:{},console};vm.createContext(context);vm.runInContext(engineSrc,context);const audit=context.window.LTUQuestionEngine.audit();
ok(audit.count===20000&&audit.uniqueIds===20000&&audit.uniqueSignatures===20000&&audit.duplicates===0,'20,000 question bank is unique');
ok(Object.keys(audit.byType||{}).length===12,'question bank covers 12 competency types');
const practice=await read('api/practice.js'),practiceUi=await read('practice-ui-v4.js');ok(practice.includes('used_count<3')&&practice.includes("AT TIME ZONE 'Asia/Taipei'"),'Free 3 quota is server-enforced by Taipei day');ok(practice.includes('learningModelUpdated:complete'),'Free answers do not update long-term weakness');ok(practice.includes('LIMIT 20000'),'seen history supports full bank');ok(practiceUi.includes("if(!me?.authenticated){showAuth(d);return}"),'practice requires real login');ok(practiceUi.includes('免費題數驗證暫時無法連線'),'Free quota fails closed');
const authUi=await read('auth-ui-v2.js');ok(authUi.includes('/api/auth/signup')&&authUi.includes('/api/auth/login')&&authUi.includes('/api/auth/logout'),'Auth V2 uses server account APIs');ok(authUi.includes('/api/newebpay/create')&&authUi.includes('/api/paypal/create'),'Auth V2 exposes real Complete payment');
const launch=await read('launch-ui-v1.js');ok(launch.includes('免費開始 3 題')&&launch.includes("['examguide','dashboard','daily','wrongbook','notes','global','admin']")&&launch.includes("if(plans){plans.style.display='block'"),'launch UI keeps the single plans section and removes legacy student flow');ok(launch.includes("dispatch('ltu:start-practice',{mode:'core'})"),'homepage Free CTA starts the real practice flow');
const preview=await read('complete-preview-v1.js');ok(preview.includes('AI COMPLETE 範例｜SAMPLE')&&preview.includes('示意資料，不是你的正式學習報告'),'public Complete preview is unmistakably labeled as sample data');ok(preview.includes("location.href='/complete.html'"),'paid users can enter a separate Complete member portal');
const portal=await read('complete-portal-v1.js');ok(portal.includes('請先登入 Complete 會員'),'unpaid users are gated from the real Complete portal');ok(portal.includes('以下是你的帳號資料，不是範例'),'paid portal distinguishes live account data from examples');ok(portal.includes('AI 記憶出題')&&portal.includes('AI 筆記')&&portal.includes('Weekly Mock')&&portal.includes('歷屆題')&&portal.includes('弱點分析'),'real Complete portal exposes the five core functions');
const notebookApi=await read('api/notebook.js'),notebookUi=await read('notebook-ui-v2.js');ok(notebookApi.includes("m.expires_at>NOW()")&&notebookApi.includes('level===3?21:30'),'Notebook checks expiry and spaced review');ok(notebookUi.includes('/api/notebook/list'),'Notebook V2 reads account notes');
const progress=await read('api/progress.js');ok(progress.includes('items.length!==64')&&progress.includes('items.slice(0,43)')&&progress.includes('items.slice(43)'),'Weekly Mock is 43+21 / 64 questions');ok(progress.includes('jsonb_to_recordset'),'Weekly Mock uses batch DB writes');
const product=await read('product-core-v1.js');ok(product.includes("take(12,['vocabulary'])")&&product.includes("take(21,['listening'])"),'Product Core dynamically assembles Weekly Mock');ok(product.includes('AI 筆記')&&product.includes('Weekly Mock')&&product.includes('歷屆')&&product.includes('弱點分析'),'Complete core features are surfaced');
const payment=await read('api/payment.js'),authMe=await read('api/auth-me.js');ok(payment.includes("locked.status==='paid'"),'payment activation is idempotent');ok(payment.includes('/#payment-success'),'payment returns to current homepage');ok(authMe.includes("status='expired'"),'expired Complete status is enforced');
const build=await read('scripts/build-ui.mjs');for(const required of ['question-engine-v2.js','practice-ui-v4.js','notebook-ui-v2.js','auth-ui-v2.js','product-core-v1.js','launch-ui-v1.js','complete-preview-v1.js','complete-portal-v1.js','membership-sync-v1.js','cute-theme-v1.js'])ok(build.includes(required),`build includes ${required}`);ok(build.includes("files=['final-v3.html']"),'mobile shell uses one UI layer');ok(build.includes("public/complete.html"),'build emits a dedicated Complete member page');ok(!build.includes("Buffer.from(heroB64,'base64')"),'build does not overwrite the verified hero with legacy base64');
console.log('\nCAP PRODUCT QA PASSED');console.log(JSON.stringify(audit,null,2));
