// Source: https://globalednews.com/study-abroad/student-start.html — checked 2026-09-19
export const diyOptions = {
  "start-country": [
    "還沒決定",
    "英國",
    "加拿大",
    "美國",
    "澳洲",
    "歐洲",
    "日本",
    "新加坡",
    "香港"
  ],
  "start-major": [
    "還沒決定",
    "Computer Science",
    "AI",
    "Data Science",
    "Engineering",
    "Business",
    "Finance",
    "Accounting",
    "Economics",
    "Psychology",
    "Biomedical Sciences",
    "Medicine",
    "Dentistry",
    "Pharmacy",
    "Art & Design",
    "Animation",
    "Film Production",
    "Architecture",
    "Fashion",
    "Music Performance",
    "Music Production",
    "Composition",
    "Communication",
    "International Relations",
    "健康科學 · Health Sciences",
    "數學 · Mathematics",
    "新聞學 · Journalism",
    "農業科學 · Agriculture",
    "生物學 · Biology",
    "化學 · Chemistry",
    "犯罪學 · Criminology",
    "教育學 · Education",
    "英語文學 · English",
    "環境科學與研究 · Environmental Science",
    "歷史學 · History",
    "人類發展與家庭研究 · Human Development",
    "人文與博雅研究 · Humanities",
    "跨領域研究 · Interdisciplinary Studies",
    "運動科學 · Kinesiology",
    "護理學 · Nursing",
    "營養科學 · Nutrition",
    "物理學 · Physics",
    "公共衛生 · Public Health",
    "公共政策 · Public Policy",
    "社會工作 · Social Work",
    "社會學 · Sociology",
    "統計學 · Statistics",
    "戲劇與表演研究 · Theatre"
  ],
  "start-goal": [
    "還沒決定",
    "名校／研究",
    "就業",
    "Co-op／實習",
    "專業執照／認證",
    "實務導向",
    "藝術設計",
    "音樂／表演"
  ],
  "start-curriculum": [
    "尚未選擇",
    "台灣普通高中",
    "OSSD",
    "IB",
    "A-Level",
    "AP／美式高中",
    "其他國際課程"
  ],
  "start-grade": [
    "尚未選擇",
    "90% 以上／A 水準",
    "85–89%",
    "80–84%",
    "75–79%",
    "70–74%",
    "70% 以下"
  ],
  "start-english": [
    "尚未選擇",
    "IELTS 7.0+／同等",
    "IELTS 6.5 左右／同等",
    "IELTS 6.0 左右／同等",
    "目前約 IELTS 5.5／同等",
    "尚未考英文"
  ],
  "start-budget": [
    "尚未選擇",
    "希望控制總成本",
    "中等預算",
    "可以接受高學費換資源／名校"
  ],
  "start-need": [
    "尚未選擇",
    "先找適合的大學",
    "確認我能不能申請",
    "確認要準備哪些文件",
    "比較 Offer"
  ]
} as const;
