export const countries=['加拿大','英國','澳洲','紐西蘭','美國','日本','新加坡','香港','歐洲','德國','荷蘭','其他歐洲','其他亞洲','台灣'];
export const stages=['選校規劃','準備申請','已送出申請','Conditional Offer','補件中','Unconditional Offer','接受錄取','已入學','撤回／未錄取'];
export const guide:any={
 '加拿大':{platform:'安大略省大學：OUAC；其他省份依大學指定平台',url:'https://www.ouac.on.ca/guide/undergrad-guide/',timing:'各校、科系、補充申請及獎學金期限不同；逐校登記截止日。',entry:'以多倫多大學為例：OSSD 加六科 4U/M，包含 ENG4U／EAE4U；必修與分數須另查目標科系。六科不是完整 OSSD 畢業條件，也不是所有國家的統一門檻。',entryUrl:'https://future.utoronto.ca/requirements-canadian-high-schools',visa:'錄取信 LOA、護照、財力證明，並確認是否須 PAL/TAL；魁北克另查 CAQ。依 IRCC 個人清單補體檢、生物辨識及其他資料。',visaUrl:'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/get-documents.html',applyUrl:'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/apply.html',after:'核准後核對護照及核准文件、入境所需文件；入境取得學習許可時核對個資、學校及效期。'},
 '英國':{platform:'UCAS（多數全日制學士）；其他課程確認校方渠道',url:'https://www.ucas.com/applying/applying-to-university/dates-and-deadlines-for-uni-applications',timing:'2027 入學：多數科系 2027/01/13 英國時間 18:00；牛津、劍橋及多數醫／牙／獸醫為 2026/10/15 英國時間 18:00。以課程頁為準。',entry:'OSSD 科數、指定科目及均分依大學要求；台灣高中成績可能需預科、學測或其他資格。不可把 OSSD 百分比直接當成台灣成績門檻。',entryUrl:'https://www.bristol.ac.uk/international/countries/taiwan.html',visa:'核對 CAS、有效護照與適用財力／英語證明；依國籍、年齡及居住史確認其他文件。由 GOV.UK 申請 Student visa，完成身分驗證。',visaUrl:'https://www.gov.uk/student-visa',applyUrl:'https://www.gov.uk/student-visa/apply',after:'核對 eVisa 與 UKVI 帳戶連結的護照；確認允許入境日期及簽證條件。'},
 '美國':{platform:'Common App 或大學自有平台',url:'https://www.commonapp.org/apply/first-year-students/',timing:'逐校確認 EA／ED／RD，以及作品集、獎學金與財力資料期限；ED 的承諾條款須先讀清楚。',entry:'依校方評估完整高中紀錄、課程難度與補充材料；SAT／ACT 政策逐校逐年查核，不預設一律免考。',entryUrl:'https://www.commonapp.org/apply/first-year-students/',visa:'適用 F-1 者先取得 I-20、繳 SEVIS I-901、填 DS-160，依申請地使領館流程預約。準備護照、確認頁、照片、I-20 與財力／學業證明。先確認國籍及身分是否適用。',visaUrl:'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html',applyUrl:'https://ceac.state.gov/genniv/',after:'核對簽證與 I-20；新生 F/M 原則上不得早於課程開始前 30 天入境。入境後核對 I-94 並向學校報到。'},
 '澳洲':{platform:'大學官方申請系統或校方指定渠道',url:'https://www.studyaustralia.gov.au/',timing:'依校方 intake 逐一登記；確認截止日與額滿提早關閉規則。',entry:'查明 OSSD／台灣資格的校方換算、指定科目、英語與專業附加要求。',entryUrl:'https://www.studyaustralia.gov.au/',visa:'依 Student visa subclass 500 官方檢核清單確認 CoE、OSHC、Genuine Student、財力及身分證明等適用項目。',visaUrl:'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500',applyUrl:'https://online.immi.gov.au/lusc/login',after:'核對核准通知、入境日期、保險期間與簽證條件；安排校方報到。'},
};
export const fallback={platform:'依目標大學官方招生頁確認',url:'',timing:'尚未確認；請先填入國家、學校、科系及入學年度。',entry:'學歷認定、科數、分數、語言與作品集要求待校系官方資料查核。',entryUrl:'',visa:'依國籍、居住地與目的國官方規定確認簽證類別及文件；未確認前不套用其他國家的流程。',visaUrl:'',applyUrl:'',after:'核對入境資格、護照、保險、住宿、註冊期限與居留規定。'};
export const applicationFields=[['university','大學名稱'],['program','科系／課程全名'],['campus','校區'],['intake','入學年度／月份'],['courseCode','課程代碼'],['officialUrl','課程官方網址'],['ossdRequirement','OSSD 科數／必修／分數'],['taiwanRequirement','台灣學歷／學測／成績門檻'],['englishRequirement','英語總分／單科要求'],['materials','申請文件與補充材料'],['platform','申請平台'],['platformUrl','平台網址'],['platformNotes','填表注意事項'],['deadline','申請截止日'],['deadlineZone','截止時間與時區'],['tuition','學費金額'],['currency','幣別'],['feePeriod','每年／全課程'],['feeYear','學費適用年度'],['feeStatus','國際生／本地生費率'],['feeSource','學費官方來源'],['requirementSource','門檻官方來源'],['checkedAt','資料查核日期'],['applicationId','申請編號'],['submittedAt','送件日期'],['offerDate','錄取日期'],['conditions','Conditional Offer 條件'],['conditionsDeadline','補件截止日'],['supplementStatus','補件內容／寄送／收件確認'],['unconditionalDate','Unconditional Offer 日期'],['acceptanceDeadline','接受錄取期限'],['deposit','訂金金額／期限／已付日期'],['accommodation','宿舍申請狀態／宿舍名稱'],['accommodationDeadline','宿舍截止日'],['accommodationUrl','宿舍申請網址'],['accommodationNotes','房型／費用／合約／取消條款'],['visaType','簽證類別／是否適用'],['visaDocuments','簽證文件清單'],['visaPlatform','簽證申請網站'],['visaSteps','簽證流程及注意事項'],['visaSubmitted','簽證送件日期'],['biometrics','生物辨識／面談／體檢'],['visaApproved','簽證核准日期'],['visaExpiry','簽證效期'],['arrival','預計入境日期'],['postVisa','核准後核對／保險／報到事項'],['nextAction','下一步'],['nextDue','下次追蹤日期']] as const;
export function preparation(s:any){let lines=['先確認入學年度、國籍／身分、申請資格及完整高中成績單。'];if(/工程|資訊|數理|CS|IT/i.test(s.major))lines.push('理工選課討論：檢查 ENG4U、MHF4U、MCV4U，並逐校確認 SPH4U／SCH4U 等先修。這是查核方向，非已確認必修清單。');if(/商|財|管理|精算|統計/.test(s.major))lines.push('商管選課討論：核對 ENG4U 與數學要求；精算／經濟／統計特別確認微積分先修。');if(/醫|牙|獸|生物|生命/.test(s.major))lines.push('醫療生命科學：確認是否高中可直入、指定理科、入學測驗與面試，不把醫學院與一般生科入學條件混用。');if(/藝術|建築|設計/.test(s.major))lines.push('藝術設計：確認作品集、面試及額外提交平台與期限。');if(!s.ossdCourses)lines.push('尚缺 OSSD 已修／在修科目與成績，不能計算尚需幾科。');if(!s.taiwanAverage)lines.push('尚缺台灣成績；保留待補，不以 0 分或推測數字替代。');return lines;}
