import crypto from 'crypto';
import pg from 'pg';
const { Pool } = pg;
let pool;
function db(){ if(!pool) pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3}); return pool; }
async function query(text,params=[]){ return db().query(text,params); }
function clean(n){return String(process.env[n]||'').trim()}
function normEmail(v=''){return String(v).trim().toLowerCase()}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(String(password),salt,64).toString('hex')}`}
function verifyPassword(password,stored=''){const [salt,expected]=String(stored).split(':');if(!salt||!expected)return false;const a=crypto.scryptSync(String(password),salt,64),b=Buffer.from(expected,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function cookies(req){const raw=req.headers.cookie||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(p=>{const i=p.indexOf('=');return [decodeURIComponent(i<0?p:p.slice(0,i)),decodeURIComponent(i<0?'':p.slice(i+1))]}))}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
async function createSession(userId,res){const token=crypto.randomBytes(32).toString('hex');await query('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL \'30 days\')',[userId,tokenHash(token)]);res.setHeader('Set-Cookie',`cap_ai_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000; Secure`)}
async function currentUser(req){const t=cookies(req).cap_ai_session;if(!t)return null;const {rows}=await query(`SELECT u.id,u.email,u.student_name,u.nickname,u.school,u.city,u.grade,u.guardian_email,u.track,u.international_interest,u.guardian_consent,COALESCE(m.plan,'free') membership_plan,COALESCE(m.status,'active') membership_status,m.starts_at,m.expires_at FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN memberships m ON m.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[tokenHash(t)]);return rows[0]||null}
async function requireUser(req,res){const u=await currentUser(req);if(!u){res.status(401).json({ok:false,error:'AUTH_REQUIRED'});return null}return u}
function html(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function aesEncrypt(text,key,iv){const c=crypto.createCipheriv('aes-256-cbc',Buffer.from(key),Buffer.from(iv));c.setAutoPadding(true);return Buffer.concat([c.update(text,'utf8'),c.final()]).toString('hex')}
function aesDecrypt(hex,key,iv){const d=crypto.createDecipheriv('aes-256-cbc',Buffer.from(key),Buffer.from(iv));d.setAutoPadding(true);return Buffer.concat([d.update(Buffer.from(hex,'hex')),d.final()]).toString('utf8')}
function sha256(t){return crypto.createHash('sha256').update(t).digest('hex').toUpperCase()}
function paypalCfg(){const clientId=clean('PAYPAL_CLIENT_ID'),clientSecret=clean('PAYPAL_CLIENT_SECRET'),mode=(clean('PAYPAL_MODE')||'sandbox').toLowerCase();return{clientId,clientSecret,mode,base:(mode==='production'||mode==='live')?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com',configured:!!clientId&&!!clientSecret}}
async function paypalRequest(path,opts={}){const cfg=paypalCfg();if(!cfg.configured)throw new Error('PAYPAL_NOT_CONFIGURED');const basic=Buffer.from(`${cfg.clientId}:${cfg.clientSecret}`).toString('base64');const tr=await fetch(`${cfg.base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const td=await tr.json();if(!tr.ok||!td.access_token)throw new Error('PAYPAL_AUTH_FAILED');const r=await fetch(`${cfg.base}${path}`,{...opts,headers:{Authorization:`Bearer ${td.access_token}`,'Content-Type':'application/json',Accept:'application/json',Prefer:'return=representation',...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok){console.error('PayPal API',r.status,data);throw new Error('PAYPAL_API_FAILED')}return data}
function baseUrl(){return clean('APP_BASE_URL').replace(/\/$/,'')}
async function activateMembership(order,provider,payload,paymentType=''){const client=await db().connect();try{await client.query('BEGIN');const locked=(await client.query('SELECT * FROM payment_orders WHERE id=$1 FOR UPDATE',[order.id])).rows[0];if(locked.status==='paid'){await client.query('COMMIT');return}const old=(await client.query('SELECT * FROM memberships WHERE user_id=$1 FOR UPDATE',[order.user_id])).rows[0];const previous=old?.expires_at||null;const nr=(await client.query(`SELECT GREATEST(COALESCE($1::timestamptz,NOW()),NOW())+($2::text||' days')::interval new_expiry`,[previous,order.duration_days])).rows[0].new_expiry;const starts=previous&&new Date(previous)>new Date()?(old?.starts_at||new Date()):new Date();await client.query(`INSERT INTO memberships(user_id,plan,status,starts_at,expires_at,source,updated_at) VALUES($1,'complete','active',$2,$3,$4,NOW()) ON CONFLICT(user_id) DO UPDATE SET plan='complete',status='active',starts_at=$2,expires_at=$3,source=$4,updated_at=NOW()`,[order.user_id,starts,nr,provider]);await client.query(`UPDATE payment_orders SET status='paid',payment_type=$2,paid_at=NOW(),provider_payload=$3,updated_at=NOW() WHERE id=$1`,[order.id,paymentType||provider,payload]);await client.query(`INSERT INTO membership_events(user_id,order_id,event_type,plan,previous_expires_at,new_expires_at) VALUES($1,$2,'payment_activated',$3,$4,$5)`,[order.user_id,order.id,order.plan,previous,nr]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK').catch(()=>{});throw e}finally{client.release()}}
export default async function handler(req,res){
  const route=String(req.query.route||'').replace(/^\/+|\/+$/g,'');
  try{
    if(route==='auth/signup'&&req.method==='POST'){const b=req.body||{},email=normEmail(b.email),pw=String(b.password||''),name=String(b.studentName||'').trim();if(!email.includes('@'))return res.status(400).json({ok:false,error:'INVALID_EMAIL'});if(pw.length<8)return res.status(400).json({ok:false,error:'PASSWORD_TOO_SHORT'});if(!name)return res.status(400).json({ok:false,error:'STUDENT_NAME_REQUIRED'});try{const {rows}=await query(`INSERT INTO users(email,password_hash,student_name,nickname,school,city,grade,guardian_email,track,international_interest,guardian_consent) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,email,student_name,nickname,school,city,grade,guardian_email,track`,[email,hashPassword(pw),name,String(b.nickname||'').trim()||null,String(b.school||'').trim()||null,String(b.city||'').trim()||null,String(b.grade||'').trim()||null,normEmail(b.guardianEmail)||null,String(b.track||'cap'),Boolean(b.internationalInterest),Boolean(b.guardianConsent)]);await query("INSERT INTO memberships(user_id,plan,status) VALUES($1,'free','active') ON CONFLICT(user_id) DO NOTHING",[rows[0].id]);await createSession(rows[0].id,res);return res.status(201).json({ok:true,user:rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({ok:false,error:'EMAIL_ALREADY_REGISTERED'});throw e}}
    if(route==='auth/login'&&req.method==='POST'){const email=normEmail(req.body?.email),pw=String(req.body?.password||'');const {rows}=await query('SELECT * FROM users WHERE email=$1 LIMIT 1',[email]);const u=rows[0];if(!u||!verifyPassword(pw,u.password_hash))return res.status(401).json({ok:false,error:'INVALID_LOGIN'});await createSession(u.id,res);return res.json({ok:true})}
    if(route==='auth/logout'&&req.method==='POST'){const t=cookies(req).cap_ai_session;if(t)await query('DELETE FROM sessions WHERE token_hash=$1',[tokenHash(t)]).catch(()=>{});res.setHeader('Set-Cookie','cap_ai_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0; Secure');return res.json({ok:true})}
    if(route==='auth/me'&&req.method==='GET'){const u=await currentUser(req);if(!u)return res.json({ok:true,authenticated:false});return res.json({ok:true,authenticated:true,user:{id:u.id,email:u.email,studentName:u.student_name,nickname:u.nickname,school:u.school,city:u.city,grade:u.grade,guardianEmail:u.guardian_email,track:u.track,membershipPlan:u.membership_plan,membershipStatus:u.membership_status,startsAt:u.starts_at,expiresAt:u.expires_at}})}
    if(route==='orders/latest'&&req.method==='GET'){const u=await requireUser(req,res);if(!u)return;const {rows}=await query('SELECT order_no,plan,amount,status,provider,created_at,updated_at FROM payment_orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[u.id]);return res.json({ok:true,order:rows[0]||null})}
    if(route==='system/status'){let connected=false,schema=false;try{await query('SELECT 1');connected=true;const r=await query("SELECT to_regclass('public.users') users,to_regclass('public.memberships') memberships,to_regclass('public.payment_orders') orders");schema=!!r.rows[0]?.users&&!!r.rows[0]?.memberships&&!!r.rows[0]?.orders}catch{}const checks={DATABASE_URL:!!process.env.DATABASE_URL,NEWEBPAY_MERCHANT_ID:!!clean('NEWEBPAY_MERCHANT_ID'),NEWEBPAY_HASH_KEY:!!clean('NEWEBPAY_HASH_KEY'),NEWEBPAY_HASH_IV:!!clean('NEWEBPAY_HASH_IV'),APP_BASE_URL:!!baseUrl()};const paymentConfigured=checks.NEWEBPAY_MERCHANT_ID&&checks.NEWEBPAY_HASH_KEY&&checks.NEWEBPAY_HASH_IV;return res.json({ok:true,databaseConnected:connected,schemaReady:schema,paymentConfigured,paymentMode:clean('NEWEBPAY_MODE')||'test',checks,ready:connected&&schema&&paymentConfigured&&checks.APP_BASE_URL})}
    if(route==='system/paypal-diagnostics'){const c=paypalCfg();return res.json({ok:true,configured:c.configured,mode:c.mode,apiBase:c.base,clientIdConfigured:!!c.clientId,clientSecretConfigured:!!c.clientSecret})}
    if(route==='system/newebpay-diagnostics'){const id=clean('NEWEBPAY_MERCHANT_ID'),k=clean('NEWEBPAY_HASH_KEY'),iv=clean('NEWEBPAY_HASH_IV'),mode=(clean('NEWEBPAY_MODE')||'test').toLowerCase();return res.json({ok:true,mode,mpgVersion:'2.0',gateway:mode==='production'?'https://core.newebpay.com/MPG/mpg_gateway':'https://ccore.newebpay.com/MPG/mpg_gateway',merchantIdMasked:id.length>6?`${id.slice(0,3)}***${id.slice(-3)}`:'***',merchantIdLength:id.length,hashKeyLength:k.length,hashIvLength:iv.length,merchantConfigured:!!id,hashKeyConfigured:!!k,hashIvConfigured:!!iv,keyLengthsValid:k.length===32&&iv.length===16})}
    if(route==='paypal/create'&&req.method==='POST'){const u=await requireUser(req,res);if(!u)return;const plan=String(req.body?.plan||'').toLowerCase(),p=plan==='annual'?{amount:15000,days:365,item:'AI Complete 年繳 365 天'}:plan==='monthly'?{amount:1500,days:30,item:'AI Complete 月繳 30 天'}:null;if(!p)return res.status(400).json({ok:false,error:'INVALID_PLAN'});const orderNo=`PP_${plan==='annual'?'Y':'M'}_${Math.floor(Date.now()/1000)}_${crypto.randomBytes(3).toString('hex')}`.slice(0,30);const ins=await query(`INSERT INTO payment_orders(order_no,user_id,plan,amount,duration_days,status,provider) VALUES($1,$2,$3,$4,$5,'pending','paypal') RETURNING id`,[orderNo,u.id,plan,p.amount,p.days]);const order=await paypalRequest('/v2/checkout/orders',{method:'POST',headers:{'PayPal-Request-Id':orderNo},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{reference_id:orderNo,custom_id:orderNo,description:p.item,amount:{currency_code:'TWD',value:String(p.amount)}}],application_context:{brand_name:'LTU Education Center',locale:'zh-TW',user_action:'PAY_NOW',return_url:`${baseUrl()}/api/paypal/return`,cancel_url:`${baseUrl()}/final-v18.html#paypal-cancelled`}})});await query('UPDATE payment_orders SET trade_no=$2,provider_payload=$3,updated_at=NOW() WHERE id=$1',[ins.rows[0].id,order.id,order]);const approve=order.links?.find(x=>x.rel==='approve')?.href;if(!approve)return res.status(502).json({ok:false,error:'PAYPAL_APPROVAL_URL_MISSING'});return res.redirect(303,approve)}
    if(route==='paypal/return'&&req.method==='GET'){const token=String(req.query.token||'');if(!token)return res.status(400).send('MISSING_PAYPAL_ORDER');const {rows}=await query("SELECT * FROM payment_orders WHERE provider='paypal' AND trade_no=$1 LIMIT 1",[token]);const order=rows[0];if(!order)return res.status(404).send('ORDER_NOT_FOUND');if(order.status==='paid')return res.redirect(303,`${baseUrl()}/final-v18.html#paypal-success`);const cap=await paypalRequest(`/v2/checkout/orders/${encodeURIComponent(token)}/capture`,{method:'POST',body:'{}'});const c=cap?.purchase_units?.[0]?.payments?.captures?.[0];if(cap.status!=='COMPLETED'||c?.status!=='COMPLETED'||c?.amount?.currency_code!=='TWD'||Number(c?.amount?.value)!==Number(order.amount)){await query("UPDATE payment_orders SET status='failed',provider_payload=$2,updated_at=NOW() WHERE id=$1",[order.id,cap]);return res.redirect(303,`${baseUrl()}/final-v18.html#paypal-failed`)}await activateMembership(order,'paypal',cap,'paypal');return res.redirect(303,`${baseUrl()}/final-v18.html#paypal-success`)}
    if(route==='newebpay/create'&&req.method==='POST'){const u=await requireUser(req,res);if(!u)return;const plan=String(req.body?.plan||'').toLowerCase(),p=plan==='annual'?{amount:15000,days:365,item:'AI Complete 年繳 365 天'}:plan==='monthly'?{amount:1500,days:30,item:'AI Complete 月繳 30 天'}:null;if(!p)return res.status(400).json({ok:false,error:'INVALID_PLAN'});const mid=clean('NEWEBPAY_MERCHANT_ID'),key=clean('NEWEBPAY_HASH_KEY'),iv=clean('NEWEBPAY_HASH_IV'),mode=(clean('NEWEBPAY_MODE')||'test').toLowerCase();if(!mid||key.length!==32||iv.length!==16)return res.status(503).json({ok:false,error:'PAYMENT_NOT_CONFIGURED'});const stamp=Math.floor(Date.now()/1000),orderNo=`AIC_${plan==='annual'?'Y':'M'}_${stamp}_${crypto.randomBytes(3).toString('hex')}`.slice(0,30);await query(`INSERT INTO payment_orders(order_no,user_id,plan,amount,duration_days,status,provider) VALUES($1,$2,$3,$4,$5,'pending','newebpay')`,[orderNo,u.id,plan,p.amount,p.days]);const params=new URLSearchParams({MerchantID:mid,RespondType:'JSON',TimeStamp:String(stamp),Version:'2.0',MerchantOrderNo:orderNo,Amt:String(p.amount),ItemDesc:p.item,LoginType:'0',ReturnURL:`${baseUrl()}/api/newebpay/return`,NotifyURL:`${baseUrl()}/api/newebpay/notify`,ClientBackURL:`${baseUrl()}/final-v18.html#upgradeV16`,WEBATM:'1',VACC:'1',CVS:'1',BARCODE:'1',Email:u.email});const ti=aesEncrypt(params.toString(),key,iv),ts=sha256(`HashKey=${key}&${ti}&HashIV=${iv}`),gateway=mode==='production'?'https://core.newebpay.com/MPG/mpg_gateway':'https://ccore.newebpay.com/MPG/mpg_gateway';res.setHeader('Content-Type','text/html; charset=utf-8');return res.send(`<!doctype html><meta charset="utf-8"><p>正在前往藍新金流安全付款頁…</p><form id="p" method="POST" action="${gateway}"><input type="hidden" name="MerchantID" value="${html(mid)}"><input type="hidden" name="TradeInfo" value="${html(ti)}"><input type="hidden" name="TradeSha" value="${html(ts)}"><input type="hidden" name="Version" value="2.0"></form><script>p.submit()</script>`)}
    if(route==='newebpay/return'&&req.method==='POST')return res.redirect(303,`${baseUrl()}/final-v18.html#upgradeV16`);
    if(route==='newebpay/notify'&&req.method==='POST'){const key=clean('NEWEBPAY_HASH_KEY'),iv=clean('NEWEBPAY_HASH_IV'),mid=clean('NEWEBPAY_MERCHANT_ID'),ti=req.body?.TradeInfo,ts=String(req.body?.TradeSha||'').toUpperCase();if(!ti||!ts)return res.status(400).send('MISSING_PAYMENT_DATA');if(ts!==sha256(`HashKey=${key}&${ti}&HashIV=${iv}`))return res.status(400).send('INVALID_TRADESHA');const data=JSON.parse(aesDecrypt(ti,key,iv)),r=data.Result||{},orderNo=String(r.MerchantOrderNo||'');if(r.MerchantID&&r.MerchantID!==mid)return res.status(400).send('MERCHANT_MISMATCH');const {rows}=await query('SELECT * FROM payment_orders WHERE order_no=$1 LIMIT 1',[orderNo]);const order=rows[0];if(!order)return res.status(404).send('ORDER_NOT_FOUND');if(data.Status!=='SUCCESS'||Number(r.Amt)!==Number(order.amount)){await query("UPDATE payment_orders SET status='failed',provider_payload=$2,updated_at=NOW() WHERE id=$1",[order.id,data]);return res.send('SUCCESS')}await activateMembership(order,'newebpay',data,r.PaymentType||'newebpay');return res.send('SUCCESS')}
    return res.status(404).json({ok:false,error:'NOT_FOUND',route});
  }catch(e){console.error('CAP API error',route,e);return res.status(500).json({ok:false,error:e.message||'SERVER_ERROR'})}
}
