import crypto from 'crypto';
import pg from 'pg';
const {Pool}=pg;
let pool;
function db(){if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3});return pool}
async function q(t,p=[]){return db().query(t,p)}
function cookies(req){const raw=req.headers.cookie||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(p=>{const i=p.indexOf('=');return [decodeURIComponent(i<0?p:p.slice(0,i)),decodeURIComponent(i<0?'':p.slice(i+1))]}))}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
async function user(req){const t=cookies(req).cap_ai_session;if(!t)return null;const {rows}=await q(`SELECT u.id,COALESCE(m.plan,'free') plan,COALESCE(m.status,'active') status FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN memberships m ON m.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[tokenHash(t)]);return rows[0]||null}
async function schema(){await q(`CREATE TABLE IF NOT EXISTS ai_notebook(id BIGSERIAL PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,question_id TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL,detail JSONB NOT NULL DEFAULT '{}'::jsonb,mastery_level INT NOT NULL DEFAULT 0,review_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,question_id,category))`);await q(`CREATE INDEX IF NOT EXISTS ai_notebook_user_time_idx ON ai_notebook(user_id,updated_at DESC)`);await q(`CREATE INDEX IF NOT EXISTS ai_notebook_review_idx ON ai_notebook(user_id,review_at)`)}
function safe(v,max=600){return String(v||'').trim().slice(0,max)}
function noteSet(b){const id=safe(b.questionId,80),type=safe(b.type,40),skill=safe(b.competency||type,80),grammar=safe(b.grammarFocus,140),stem=safe(b.stem,700),exp=safe(b.explanation,700),opts=Array.isArray(b.options)?b.options.slice(0,5).map(x=>safe(x,180)):[];const selected=Number.isInteger(b.selectedIndex)?b.selectedIndex:null,answer=Number.isInteger(b.correctAnswerIndex)?b.correctAnswerIndex:null;const detail={type,skill,grammarFocus:grammar,stem,options:opts,selectedIndex:selected,correctAnswerIndex:answer};const out=[];const add=(category,title,content)=>out.push({category,title:safe(title,160),content:safe(content||exp||stem,900),detail});
add('mistake',`錯因｜${skill}`,exp||'這一題需要重新確認題目線索與選項差異。');
add('weakness',`弱點｜${skill}`,`這次錯題已加入「${skill}」弱點追蹤，之後會安排同能力、不同情境的變式題。`);
if(grammar||type==='grammar')add('grammar',`文法｜${grammar||skill}`,exp||`重新整理 ${grammar||skill} 的判斷規則。`);
if(type==='vocabulary')add('vocabulary',`單字｜${skill}`,exp||stem);
if(type==='collocation'||type==='connectors'||type==='cloze')add('phrase',`片語／搭配｜${skill}`,exp||stem);
if(type==='sentencePattern')add('sentence_pattern',`句型｜${grammar||skill}`,exp||stem);
if(['detail','mainIdea','reference','inference','sequence','listening'].includes(type))add('strategy',`策略｜${skill}`,exp||'回到題目線索，找出支持答案的文字或聽力證據。');
return {id,notes:out}}
export default async function handler(req,res){try{await schema();const u=await user(req);if(!u)return res.status(401).json({ok:false,error:'AUTH_REQUIRED'});const complete=u.plan==='complete'&&u.status==='active';const route=String(req.query.notebookRoute||'').replace(/^\/+|\/+$/g,'');
if(route==='summary'&&req.method==='GET'){if(!complete)return res.json({ok:true,complete:false,sample:true});const {rows}=await q(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE category='vocabulary')::int vocabulary,COUNT(*) FILTER(WHERE category='phrase')::int phrase,COUNT(*) FILTER(WHERE category='grammar')::int grammar,COUNT(*) FILTER(WHERE category='sentence_pattern')::int sentence_pattern,COUNT(*) FILTER(WHERE category='mistake')::int mistake,COUNT(*) FILTER(WHERE category='weakness')::int weakness,COUNT(*) FILTER(WHERE category='strategy')::int strategy,COUNT(*) FILTER(WHERE review_at IS NOT NULL AND review_at<=NOW())::int due FROM ai_notebook WHERE user_id=$1`,[u.id]);let top=[];try{top=(await q(`SELECT skill,weight::float FROM practice_weakness WHERE user_id=$1 ORDER BY weight DESC LIMIT 5`,[u.id])).rows}catch{}return res.json({ok:true,complete:true,counts:rows[0],topWeakness:top})}
if(route==='list'&&req.method==='GET'){if(!complete)return res.status(403).json({ok:false,error:'COMPLETE_REQUIRED'});const cat=safe(req.query.category,40);const params=[u.id],where=cat&&cat!=='all'?' AND category=$2':'';if(where)params.push(cat);const {rows}=await q(`SELECT id,question_id,category,title,content,detail,mastery_level,review_at,created_at,updated_at FROM ai_notebook WHERE user_id=$1${where} ORDER BY CASE WHEN review_at IS NOT NULL AND review_at<=NOW() THEN 0 ELSE 1 END,updated_at DESC LIMIT 120`,params);return res.json({ok:true,items:rows})}
if(route==='save'&&req.method==='POST'){if(!complete)return res.json({ok:true,persisted:false});const b=req.body||{};if(b.correct===true)return res.json({ok:true,persisted:false});const {id,notes}=noteSet(b);if(!id)return res.status(400).json({ok:false,error:'QUESTION_ID_REQUIRED'});for(const n of notes){await q(`INSERT INTO ai_notebook(user_id,question_id,category,title,content,detail,review_at) VALUES($1,$2,$3,$4,$5,$6,NOW()+INTERVAL '3 days') ON CONFLICT(user_id,question_id,category) DO UPDATE SET title=EXCLUDED.title,content=EXCLUDED.content,detail=EXCLUDED.detail,review_at=LEAST(COALESCE(ai_notebook.review_at,EXCLUDED.review_at),EXCLUDED.review_at),updated_at=NOW()`,[u.id,id,n.category,n.title,n.content,n.detail])}return res.json({ok:true,persisted:true,count:notes.length})}
if(route==='review'&&req.method==='POST'){if(!complete)return res.status(403).json({ok:false,error:'COMPLETE_REQUIRED'});const id=Number(req.body?.id),correct=Boolean(req.body?.correct);if(!Number.isFinite(id))return res.status(400).json({ok:false,error:'INVALID_NOTE'});const cur=(await q(`SELECT mastery_level FROM ai_notebook WHERE id=$1 AND user_id=$2`,[id,u.id])).rows[0];if(!cur)return res.status(404).json({ok:false,error:'NOTE_NOT_FOUND'});const level=correct?Math.min(4,Number(cur.mastery_level||0)+1):0;const days=level===0?1:level===1?3:level===2?7:level===3?21:30;await q(`UPDATE ai_notebook SET mastery_level=$3,review_at=NOW()+($4::text||' days')::interval,updated_at=NOW() WHERE id=$1 AND user_id=$2`,[id,u.id,level,days]);return res.json({ok:true,masteryLevel:level,nextReviewDays:days})}
return res.status(404).json({ok:false,error:'NOT_FOUND'})}catch(e){console.error('notebook api',e);return res.status(500).json({ok:false,error:'NOTEBOOK_API_FAILED'})}}