import crypto from 'crypto';
import pg from 'pg';
const {Pool}=pg;
let pool;
function db(){if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3});return pool}
async function q(t,p=[]){return db().query(t,p)}
function clean(n){return String(process.env[n]||'').trim()}
function cookies(req){const raw=req.headers.cookie||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(p=>{const i=p.indexOf('=');return[decodeURIComponent(i<0?p:p.slice(0,i)),decodeURIComponent(i<0?'':p.slice(i+1))]}))}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
function body(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return Object.fromEntries(new URLSearchParams(req.body));return{}}
async function user(req){const t=cookies(req).cap_ai_session;if(!t)return null;const {rows}=await q(`SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[tokenHash(t)]);return rows[0]||null}
function baseUrl(){return clean('APP_BASE_URL').replace(/\/$/,'')}
function plan(v){v=String(v||'').toLowerCase();return v==='annual'?{code:'annual',amount:15000,days:365,item:'AI Complete 年繳 365 天'}:v==='monthly'?{code:'monthly',amount:1500,days:30,item:'AI Complete 月繳 30 天'}:null}
function html(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function aesEncrypt(text,key,iv){const c=crypto.createCipheriv('aes-256-cbc',Buffer.from(key),Buffer.from(iv));c.setAutoPadding(true);return Buffer.concat([c.update(text,'utf8'),c.final()]).toString('hex')}
function aesDecrypt(hex,key,iv){const d=crypto.createDecipheriv('aes-256-cbc',Buffer.from(key),Buffer.from(iv));d.setAutoPadding(true);return Buffer.concat([d.update(Buffer.from(hex,'hex')),d.final()]).toString('utf8')}
function sha256(t){return crypto.createHash('sha256').update(t).digest('hex').toUpperCase()}
function paypalCfg(){const clientId=clean('PAYPAL_CLIENT_ID'),clientSecret=clean('PAYPAL_CLIENT_SECRET'),mode=(clean('PAYPAL_MODE')||'sandbox').toLowerCase();return{clientId,clientSecret,mode,base:(mode==='production'||mode==='live')?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com',configured:!!clientId&&!!clientSecret}}
async function paypalRequest(path,opts={}){const c=paypalCfg();if(!c.configured)throw new Error('PAYPAL_NOT_CONFIGURED');const basic=Buffer.from(`${c.clientId}:${c.clientSecret}`).toString('base64');const tr=await fetch(`${c.base}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const td=await tr.json().catch(()=>({}));if(!tr.ok||!td.access_token)throw new Error('PAYPAL_AUTH_FAILED');const r=await fetch(`${c.base}${path}`,{...opts,headers:{Authorization:`Bearer ${td.access_token}`,'Content-Type':'application/json',Accept:'application/json',Prefer:'return=representation',...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok){console.error('paypal',r.status,data);throw new Error('PAYPAL_API_FAILED')}return data}
async function activate(order,provider,payload,paymentType=''){const c=await db().connect();try{await c.query('BEGIN');const locked=(await c.query('SELECT * FROM payment_orders WHERE id=$1 FOR UPDATE',[order.id])).rows[0];if(!locked){throw new Error('ORDER_NOT_FOUND')}if(locked.status==='paid'){await c.query('COMMIT');return}const old=(await c.query('SELECT * FROM memberships WHERE user_id=$1 FOR UPDATE',[locked.user_id])).rows[0];const previous=old?.expires_at||null;const nr=(await c.query(`SELECT GREATEST(COALESCE($1::timestamptz,NOW()),NOW())+($2::text||' days')::interval AS expiry`,[previous,locked.duration_days])).rows[0].expiry;const starts=previous&&new Date(previous)>new Date()?(old?.starts_at||new Date()):new Date();await c.query(`INSERT INTO memberships(user_id,plan,status,starts_at,expires_at,source,updated_at) VALUES($1,'complete','active',$2,$3,$4,NOW()) ON CONFLICT(user_id) DO UPDATE SET plan='complete',status='active',starts_at=$2,expires_at=$3,source=$4,updated_at=NOW()`,[locked.user_id,starts,nr,provider]);await c.query(`UPDATE payment_orders SET status='paid',payment_type=$2,paid_at=COALESCE(paid_at,NOW()),provider_payload=$3,updated_at=NOW() WHERE id=$1`,[locked.id,paymentType||provider,payload]);await c.query(`INSERT INTO membership_events(user_id,order_id,event_type,plan,previous_expires_at,new_expires_at) VALUES($1,$2,'payment_activated',$3,$4,$5)`,[locked.user_id,locked.id,locked.plan,previous,nr]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}}
export default async function handler(req,res){const provider=String(req.query.provider||'').toLowerCase(),route=String(req.query.paymentRoute||'').replace(/^\/+|\/+$/g,'');try{const base=baseUrl();if(!base)return res.status(503).json({ok:false,error:'APP_BASE_URL_REQUIRED'});
 if(provider==='paypal'&&route==='create'&&req.method==='POST'){const u=await user(req);if(!u)return res.status(401).json({ok:false,error:'AUTH_REQUIRED'});const p=plan(body(req).plan);if(!p)return res.status(400).json({ok:false,error:'INVALID_PLAN'});if(!paypalCfg().configured)return res.status(503).json({ok:false,error:'PAYPAL_NOT_CONFIGURED'});const orderNo=`PP_${p.code==='annual'?'Y':'M'}_${Math.floor(Date.now()/1000)}_${crypto.randomBytes(3).toString('hex')}`.slice(0,30),ins=(await q(`INSERT INTO payment_orders(order_no,user_id,plan,amount,duration_days,status,provider) VALUES($1,$2,$3,$4,$5,'pending','paypal') RETURNING id`,[orderNo,u.id,p.code,p.amount,p.days])).rows[0];const o=await paypalRequest('/v2/checkout/orders',{method:'POST',headers:{'PayPal-Request-Id':orderNo},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{reference_id:orderNo,custom_id:orderNo,description:p.item,amount:{currency_code:'TWD',value:String(p.amount)}}],application_context:{brand_name:'LTU Education Center',locale:'zh-TW',user_action:'PAY_NOW',return_url:`${base}/api/paypal/return`,cancel_url:`${base}/#payment-cancelled`}})});await q('UPDATE payment_orders SET trade_no=$2,provider_payload=$3,updated_at=NOW() WHERE id=$1',[ins.id,o.id,o]);const approve=o.links?.find(x=>x.rel==='approve')?.href;if(!approve)throw new Error('PAYPAL_APPROVAL_URL_MISSING');return res.redirect(303,approve)}
 if(provider==='paypal'&&route==='return'&&req.method==='GET'){const token=String(req.query.token||'');if(!token)return res.redirect(303,`${base}/#payment-failed`);const order=(await q("SELECT * FROM payment_orders WHERE provider='paypal' AND trade_no=$1 LIMIT 1",[token])).rows[0];if(!order)return res.redirect(303,`${base}/#payment-failed`);if(order.status==='paid')return res.redirect(303,`${base}/#payment-success`);const cap=await paypalRequest(`/v2/checkout/orders/${encodeURIComponent(token)}/capture`,{method:'POST',body:'{}'}),c=cap?.purchase_units?.[0]?.payments?.captures?.[0];if(cap.status!=='COMPLETED'||c?.status!=='COMPLETED'||c?.amount?.currency_code!=='TWD'||Number(c?.amount?.value)!==Number(order.amount)){await q("UPDATE payment_orders SET status='failed',provider_payload=$2,updated_at=NOW() WHERE id=$1",[order.id,cap]);return res.redirect(303,`${base}/#payment-failed`)}await activate(order,'paypal',cap,'paypal');return res.redirect(303,`${base}/#payment-success`)}
 if(provider==='newebpay'&&route==='create'&&req.method==='POST'){const u=await user(req);if(!u)return res.status(401).json({ok:false,error:'AUTH_REQUIRED'});const p=plan(body(req).plan);if(!p)return res.status(400).json({ok:false,error:'INVALID_PLAN'});const mid=clean('NEWEBPAY_MERCHANT_ID'),key=clean('NEWEBPAY_HASH_KEY'),iv=clean('NEWEBPAY_HASH_IV'),mode=(clean('NEWEBPAY_MODE')||'test').toLowerCase();if(!mid||key.length!==32||iv.length!==16)return res.status(503).json({ok:false,error:'PAYMENT_NOT_CONFIGURED'});const stamp=Math.floor(Date.now()/1000),orderNo=`AIC_${p.code==='annual'?'Y':'M'}_${stamp}_${crypto.randomBytes(3).toString('hex')}`.slice(0,30);await q(`INSERT INTO payment_orders(order_no,user_id,plan,amount,duration_days,status,provider) VALUES($1,$2,$3,$4,$5,'pending','newebpay')`,[orderNo,u.id,p.code,p.amount,p.days]);const params=new URLSearchParams({MerchantID:mid,RespondType:'JSON',TimeStamp:String(stamp),Version:'2.0',MerchantOrderNo:orderNo,Amt:String(p.amount),ItemDesc:p.item,LoginType:'0',ReturnURL:`${base}/api/newebpay/return`,NotifyURL:`${base}/api/newebpay/notify`,ClientBackURL:`${base}/#payment-return`,WEBATM:'1',VACC:'1',CVS:'1',BARCODE:'1',Email:u.email}),ti=aesEncrypt(params.toString(),key,iv),ts=sha256(`HashKey=${key}&${ti}&HashIV=${iv}`),gateway=mode==='production'?'https://core.newebpay.com/MPG/mpg_gateway':'https://ccore.newebpay.com/MPG/mpg_gateway';res.setHeader('Content-Type','text/html; charset=utf-8');return res.send(`<!doctype html><meta charset="utf-8"><p>正在前往藍新金流安全付款頁…</p><form id="p" method="POST" action="${gateway}"><input type="hidden" name="MerchantID" value="${html(mid)}"><input type="hidden" name="TradeInfo" value="${html(ti)}"><input type="hidden" name="TradeSha" value="${html(ts)}"><input type="hidden" name="Version" value="2.0"></form><script>document.getElementById('p').submit()</script>`)}
 if(provider==='newebpay'&&route==='return'&&(req.method==='POST'||req.method==='GET'))return res.redirect(303,`${base}/#payment-return`);
 if(provider==='newebpay'&&route==='notify'&&req.method==='POST'){const b=body(req),key=clean('NEWEBPAY_HASH_KEY'),iv=clean('NEWEBPAY_HASH_IV'),mid=clean('NEWEBPAY_MERCHANT_ID'),ti=String(b.TradeInfo||''),ts=String(b.TradeSha||'').toUpperCase();if(!ti||!ts)return res.status(400).send('MISSING_PAYMENT_DATA');if(!key||!iv||ts!==sha256(`HashKey=${key}&${ti}&HashIV=${iv}`))return res.status(400).send('INVALID_TRADESHA');const data=JSON.parse(aesDecrypt(ti,key,iv)),r=data.Result||{},orderNo=String(r.MerchantOrderNo||'');if(r.MerchantID&&r.MerchantID!==mid)return res.status(400).send('MERCHANT_MISMATCH');const order=(await q('SELECT * FROM payment_orders WHERE order_no=$1 LIMIT 1',[orderNo])).rows[0];if(!order)return res.status(404).send('ORDER_NOT_FOUND');if(order.status==='paid')return res.send('SUCCESS');if(data.Status!=='SUCCESS'||Number(r.Amt)!==Number(order.amount)){await q("UPDATE payment_orders SET status='failed',provider_payload=$2,updated_at=NOW() WHERE id=$1",[order.id,data]);return res.send('SUCCESS')}await activate(order,'newebpay',data,r.PaymentType||'newebpay');return res.send('SUCCESS')}
 return res.status(404).json({ok:false,error:'NOT_FOUND',provider,route});
}catch(e){console.error('payment api',provider,route,e);if(res.headersSent)return;return res.status(500).json({ok:false,error:e.message||'PAYMENT_API_FAILED'})}}
