"use client";
import {useEffect,useState,useRef} from 'react';
import {Search,Plus,Mic,Save,ArrowLeft,GraduationCap,Globe2,ClipboardList,Sparkles,ExternalLink,CheckCircle2,Users,AlertCircle,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import universityOptions from '@/lib/diy-universities.json';
import {diyOptions} from '@/lib/diy-options';
import {countries,stages,guide,fallback,applicationFields,preparation} from '@/lib/guides';
import {apiFetch} from '@/lib/supabase-client';
function Pick({value,onChange,options,label}:any){return <Select value={value||'待確認'} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map((x:string)=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
function Link({url,children}:any){return /^https?:\/\//.test(url||'')?<a href={url} target="_blank" rel="noreferrer">{children} <ExternalLink size={13}/></a>:null}
function Field({label,value,onChange,large=false,type='text'}:any){const ref=useRef<any>(null);const [listening,setListening]=useState(false);useEffect(()=>()=>ref.current?.abort(),[]);function voice(){if(listening){ref.current?.stop();return}const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){toast.error('此瀏覽器不支援語音辨識，請使用支援的 Chrome／Edge，或裝置鍵盤的語音輸入。');return}const r=new SR();ref.current=r;r.lang='zh-TW';r.continuous=false;r.interimResults=false;r.onresult=(e:any)=>onChange((value?value+' ':'')+e.results[0][0].transcript);r.onerror=()=>{toast.error('未取得語音，請檢查麥克風權限後重試。');setListening(false)};r.onend=()=>setListening(false);r.start();setListening(true)}return <label className={'field '+(large?'wide':'')}><span>{label}{type==='text'&&<button type="button" onClick={voice} title={'語音輸入：'+label} aria-label={'語音輸入：'+label} className={listening?'recording':''}><Mic size={15}/>{listening?'停止':''}</button>}</span>{large?<Textarea value={value||''} onChange={e=>onChange(e.target.value)} rows={3}/>:<Input value={value||''} type={type} onChange={e=>onChange(e.target.value)}/>}</label>}

const years=Array.from({length:10},(_,i)=>String(new Date().getFullYear()-1+i));
const majorOptions=[...diyOptions['start-major'].slice(1)];
const courseOptions=['ENG3U','ENG4U','ESLAO','ESLBO','ESLCO','ESLDO','ESLEO','MHF4U','MCV4U','MDM4U','SBI4U','SCH4U','SPH4U','BBB4M','BOH4M','BAT4M','ICS4U','CIA4U','HHS4U','HSB4U','AVI4M','AMU4M','OLC4O'];
const fieldOptions:Record<string,string[]>={
 '台灣就讀高中':['延平高中','復興高中','光仁高中','靜修高中','竹林高中','明道高中','彰化高商','錦和高中','曉明女中','復興商工','大明高中','宏仁高中','陽交大附中','彰化高工','僑泰高中','豐原高中','自學生'],
 '年級／屆別':['高一','高二','升高三','高三','已畢業','年級待確認'],
 '預計入學年度':years,
 '國籍／居留身分':['台灣籍','加拿大籍','美國籍','英國籍','澳洲籍','香港居民','雙重國籍','永久居民','待確認'],
 '台灣成績平均／計算期間':[...diyOptions['start-grade'].slice(1)],
 'IELTS／其他英語成績與日期':[...diyOptions['start-english'].slice(1)],
 '科系／課程全名':majorOptions,
 '幣別':['CAD','GBP','USD','AUD','NZD','EUR','JPY','SGD','HKD','TWD'],
 '每年／全課程':['每年','每學期','全課程'],
 '學費適用年度':years,
 '入學年度／月份':years.flatMap(y=>Array.from({length:12},(_,i)=>y+'/'+String(i+1).padStart(2,'0'))),
 '國際生／本地生費率':['國際生','本地生','待校方確認'],
 '申請平台':['UCAS','Common App','OUAC','EducationPlannerBC','大學官方申請系統','校方指定代辦平台'],
 '宿舍申請狀態／宿舍名稱':['未開始','準備申請','已申請','候補中','已獲分配','已付訂金','已確認入住','自行租屋','不需要宿舍'],
 '簽證類別／是否適用':['待確認','英國 Student visa','加拿大 Study permit','美國 F-1','澳洲 Student visa subclass 500','紐西蘭 Fee Paying Student Visa','不需要學生簽證'],
 '生物辨識／面談／體檢':['待確認','尚未預約','已預約','已完成','不適用'],
 '下一步':['確認志願','核對入學條件','規劃 OSSD 選課','準備英語考試','準備申請文件','送出申請','追蹤錄取','補交文件','接受錄取','繳付訂金','申請住宿','申請學生簽證','安排出發','完成報到']
};
function Choice({label,value='',onChange,options,multi=false,array=false}:any){
 const values:string[]=array?(value||[]):multi?(value?String(value).split('、'):[]):[String(value||'')];
 const known=values.filter(v=>options.includes(v));const unknown=values.filter(v=>v&&!options.includes(v));
 const [other,setOther]=useState(unknown.length>0);
 useEffect(()=>{setOther(unknown.length>0)},[JSON.stringify(unknown)]);
 const emit=(v:string[])=>onChange(array?v:multi?v.join('、'):(v[0]||''));
 return <div className="field"><span>{label}</span>{multi?<div className="choices choice-options">{options.map((v:string)=><label key={v}><Checkbox checked={known.includes(v)} onCheckedChange={yes=>emit(yes?[...values,v]:values.filter(x=>x!==v))}/>{v}</label>)}<label><Checkbox checked={other} onCheckedChange={yes=>{setOther(!!yes);if(!yes)emit(known)}}/>其他</label></div>:<Select value={unknown.length||other?'__other':value||'__empty'} onValueChange={v=>{setOther(v==='__other');if(v==='__other'){if(!unknown.length)onChange('')}else onChange(v==='__empty'?'':v)}}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__empty">請選擇／待確認</SelectItem>{options.map((v:string)=><SelectItem key={v} value={v}>{v}</SelectItem>)}<SelectItem value="__other">其他（手動／語音）</SelectItem></SelectContent></Select>}{other&&<Field label={label+'：其他／原有內容'} value={unknown.join('、')} onChange={(v:string)=>multi?emit([...known,...(v?[v]:[])]):onChange(v)} large={multi}/>}</div>
}
function SmartField(props:any){const options=props.options||fieldOptions[props.label];return options?<Choice {...props} options={options}/>:<Field {...props}/>}
function CourseRows({rows,onChange}:any){const edit=(i:number,k:string,v:string)=>onChange(rows.map((r:any,n:number)=>n===i?{...r,[k]:v}:r));return <div className="wide"><h3>OSSD 課程逐科紀錄</h3>{rows.map((r:any,i:number)=><div className="course-row" key={r.id}><Choice label="科目" value={r.code} options={courseOptions} onChange={(v:string)=>edit(i,'code',v)}/><Choice label="修課狀態" value={r.status} options={['計畫修讀','在修','已完成','待確認']} onChange={(v:string)=>edit(i,'status',v)}/><Choice label="成績（百分制）" value={r.score} options={Array.from({length:101},(_,n)=>String(100-n))} onChange={(v:string)=>edit(i,'score',v)}/><Field label="預計／實際完成日" type="date" value={r.date} onChange={(v:string)=>edit(i,'date',v)}/><Button variant="ghost" type="button" onClick={()=>onChange(rows.filter((_:any,n:number)=>n!==i))}>移除此科</Button></div>)}<Button type="button" variant="outline" onClick={()=>onChange([...rows,{id:crypto.randomUUID(),code:'',status:'計畫修讀',score:'',date:''}])}>＋ 新增 OSSD 科目</Button></div>}
function adviceSignature(s:any){return JSON.stringify(s?['countries','major','entryYear','citizenship','qualification','taiwanAverage','ielts','ossdCourses','goal','budget','need','gradePeriod','exactAverage','englishTest','ieltsExact','englishDate'].map(k=>s[k]).concat([s.applications.map((a:any)=>[a.university,a.program,a.country,a.intake])]):null)}
export default function Workspace(){
 const [students,setStudents]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[q,setQ]=useState(''),[country,setCountry]=useState('全部國家'),[view,setView]=useState('students'),[tab,setTab]=useState('profile'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[meta,setMeta]=useState<any>({}),[note,setNote]=useState(''),[noteDate,setNoteDate]=useState(new Date().toLocaleDateString('en-CA')),[noteDue,setNoteDue]=useState(''),[appIndex,setAppIndex]=useState(0),[aiBusy,setAiBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await apiFetch('/api/students');const d:any=await r.json();if(!r.ok)throw Error(d.error);setStudents(d.students);setMeta(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();try{Promise.resolve(ctx.registerTool({name:'search_students',description:'依姓名、暱稱或高中篩選目前学生清單，不修改資料。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:({query}:any)=>{if(typeof query!=='string')throw Error('query must be a string');setQ(query);return {matches:students.filter(s=>[s.name,s.nickname,s.school].some(v=>String(v).toLowerCase().includes(query.toLowerCase()))).map(s=>({name:s.name,id:s.id}))}}},{signal:c.signal})).catch(()=>{})}catch{}return()=>c.abort()},[students]);
 function update(k:string,v:any){setSelected((s:any)=>({...s,[k]:v}));setDirty(true)}
 function choose(s:any){if(dirty){toast.error('請先儲存目前紀錄，再切換學生。');return}setSelected(structuredClone(s));setTab('profile');setAppIndex(0);setNote('')}
 async function save(){if(!selected.name?.trim()){toast.error('請填寫學生姓名');return}setBusy(true);try{const r=await apiFetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(selected)});const d:any=await r.json();if(!r.ok)throw Error(d.error);setStudents(v=>v.some(x=>x.id===d.id)?v.map(x=>x.id===d.id?d:x):[...v,d]);setSelected(d);setDirty(false);toast.success('已儲存學生紀錄');if(meta.aiReady&&adviceSignature(d)!==adviceSignature(students.find(x=>x.id===d.id))){setAiBusy(true);try{const ar=await apiFetch('/api/advice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id})});const ad:any=await ar.json();if(!ar.ok)throw Error(ad.error);const sr=await apiFetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,advice:ad})});const sd:any=await sr.json();if(!sr.ok)throw Error(sd.error);setSelected(sd);setStudents(v=>v.map(x=>x.id===sd.id?sd:x));toast.success('AI 建議已自動更新並儲存')}catch(e:any){toast.error('學生資料已儲存；'+e.message)}finally{setAiBusy(false)}}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 function addStudent(){if(dirty){toast.error('請先儲存目前紀錄');return}choose({id:crypto.randomUUID(),name:'',nickname:'',school:'',cohort:'升高三',countries:[],major:'',qualification:'待確認',applications:[],notes:[],raw:[],review:'',entryYear:''})}
 function changeApp(k:string,v:any){update('applications',selected.applications.map((a:any,i:number)=>i===appIndex?{...a,[k]:v}:a))}
 function addApp(){const c=selected.countries[0]||'待確認';const g=guide[c]||fallback;update('applications',[...selected.applications,{id:crypto.randomUUID(),country:c,status:'選校規劃',visaStatus:'未開始',platform:g.platform,platformUrl:g.url,visaDocuments:g.visa,visaPlatform:g.applyUrl,postVisa:g.after,platformNotes:'姓名與護照一致；完整申報台灣及 OSSD 教育紀錄；核對校區、課程代碼、入學年度與時區。',feePeriod:'每年',checkedAt:'',materials:'待逐校確認：高中成績單、在學／畢業證明、英語成績；推薦信、文書、作品集或面試依科系。'}]);setAppIndex(selected.applications.length)}
 async function generate(){if(dirty){toast.error('請先儲存，再產生 AI 建議。');return}setAiBusy(true);try{const r=await apiFetch('/api/advice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id})});const d:any=await r.json();if(!r.ok)throw Error(d.error);update('advice',d);toast.success('建議已產生，請檢視並儲存。')}catch(e:any){toast.error(e.message)}finally{setAiBusy(false)}}
 const filtered=students.filter(s=>[s.name,s.nickname,s.school,s.major].some(x=>String(x).toLowerCase().includes(q.toLowerCase()))&&(country==='全部國家'||s.countries.includes(country)));
 const apps=students.flatMap(s=>s.applications.map((a:any)=>({...a,student:s})));
 const active=selected?.applications?.[appIndex];
 function exportData(){const b=new Blob([JSON.stringify({students,unassigned:meta.unassigned,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='LTU-升學輔導備份.json';a.click();URL.revokeObjectURL(u)}
 return <div className="app"><Toaster richColors position="top-center"/><header className="top"><div className="brand"><b>LTU<span>OSSD</span></b><div>升學輔導資料庫<small>STUDENT GUIDANCE</small></div></div><span className="private">內部輔導工作區</span><div className="top-actions"><Button variant="outline" onClick={exportData} disabled={!students.length}><Download size={16}/>匯出紀錄</Button><Button onClick={addStudent}><Plus size={17}/>新增學生</Button></div></header>
 <div className="layout"><nav className="rail"><div className="rail-title">輔導工作台</div>{[['students','學生名單',Users],['tracking','申請追蹤',ClipboardList],['review','待確認資料',AlertCircle]].map(([id,label,Icon]:any)=><button key={id} className={view===id?'active':''} onClick={()=>{if(dirty){toast.error('請先儲存');return}setView(id);setSelected(null)}}><Icon size={19}/>{label}</button>)}<div className="rail-foot"><GraduationCap size={25}/><strong>每一步，都有紀錄。</strong><p>選校 · 申請 · 錄取 · 行前</p><small>資料來源：升學意向調查<br/>升學意向＋個別諮詢調查</small></div></nav>
 <main>{error?<section className="panel"><h1>暫時無法載入</h1><p>{error}</p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">登入 ChatGPT</a><Button onClick={load}>重新載入</Button></section>:loading?<section className="panel">正在讀取學生紀錄…</section>:selected?<>
 <div className="detail-head"><Button variant="ghost" onClick={()=>{if(dirty){toast.error('請先儲存目前紀錄');return}setSelected(null)}}><ArrowLeft size={18}/>學生名單</Button><span className={dirty?'unsaved':'muted'}>{dirty?'有尚未儲存的修改':'已儲存'}</span><Button onClick={save} disabled={busy}><Save size={16}/>{busy?'儲存中…':'儲存紀錄'}</Button></div>
 <section className="student-banner"><div className="avatar">{selected.name?.slice(0,1)||'新'}</div><div><h1>{selected.name||'新增學生'} <em>{selected.nickname}</em></h1><p>{selected.school||'高中待填'}　／　{selected.cohort||'年級待確認'}</p></div><div className="banner-countries">{selected.countries.map((c:string)=><span key={c}>{c}</span>)}</div></section>
 <fieldset disabled={busy||aiBusy}><Tabs key={selected.id} value={tab} onValueChange={setTab}><TabsList className="detail-tabs"><TabsTrigger value="profile">基本資料與志願</TabsTrigger><TabsTrigger value="applications">選校與申請 {selected.applications.length}</TabsTrigger><TabsTrigger value="advice">準備方向與 AI</TabsTrigger><TabsTrigger value="notes">輔導紀錄 {selected.notes.length}</TabsTrigger><TabsTrigger value="consultations">個別諮詢 {selected.consultations?.length||0}</TabsTrigger><TabsTrigger value="source">調查原始資料</TabsTrigger></TabsList>
 <TabsContent value="profile"><section className="panel"><h2>學生基本資料</h2><div className="form-grid">{[['name','學生姓名'],['nickname','英文暱稱'],['school','台灣就讀高中'],['cohort','年級／屆別'],['entryYear','預計入學年度'],['citizenship','國籍／居留身分']].map(([k,l])=>k==='school'?<Choice key={k} label={l} value={selected[k]} options={Array.from(new Set([...fieldOptions[l],...students.map(s=>s.school).filter(Boolean)]))} onChange={(v:string)=>update(k,v)}/>:<SmartField key={k} label={l} value={selected[k]} onChange={(v:string)=>update(k,v)}/>)}<Choice label="申請資格" value={selected.qualification} onChange={(v:string)=>update('qualification',v)} options={['待確認',...diyOptions['start-curriculum'].slice(1),'台灣高中成績','OSSD＋台灣高中']}/><SmartField label="台灣成績平均／計算期間" value={selected.taiwanAverage} onChange={(v:string)=>update('taiwanAverage',v)}/><Choice label="成績計算期間" value={selected.gradePeriod} options={['高一上','高一下','高二上','高二下','高三上','高三下','高中前四學期','高中前五學期','高中六學期']} onChange={(v:string)=>update('gradePeriod',v)}/><SmartField label="IELTS／其他英語成績與日期" value={selected.ielts} onChange={(v:string)=>update('ielts',v)}/><Choice label="英語考試類型" value={selected.englishTest} options={['IELTS Academic','TOEFL iBT','PTE Academic','Duolingo English Test','尚未考試']} onChange={(v:string)=>update('englishTest',v)}/><Choice label="IELTS 精確總分（選填）" value={selected.ieltsExact} options={Array.from({length:19},(_,i)=>(i/2).toFixed(1))} onChange={(v:string)=>update('ieltsExact',v)}/><Field label="英語考試日期" type="date" value={selected.englishDate} onChange={(v:string)=>update('englishDate',v)}/><Choice label="精確台灣平均分數（選填）" value={selected.exactAverage} options={Array.from({length:101},(_,n)=>String(100-n))} onChange={(v:string)=>update('exactAverage',v)}/><CourseRows rows={selected.ossdCourseRows||[]} onChange={(rows:any[])=>{setSelected((s:any)=>({...s,ossdCourseRows:rows,ossdLegacy:s.ossdLegacy??(s.ossdCourseRows? '':s.ossdCourses||''),ossdCourses:[s.ossdLegacy??(s.ossdCourseRows?'':s.ossdCourses||''),...rows.map(r=>[r.code,r.status,r.score? r.score+'分':'',r.date].filter(Boolean).join('／'))].filter(Boolean).join('；')}));setDirty(true)}}/>{(selected.ossdLegacy||(selected.ossdCourseRows===undefined&&selected.ossdCourses))&&<p className="wide muted">原有 OSSD 紀錄（保留）：{selected.ossdLegacy||selected.ossdCourses}</p>}</div></section>
 <section className="panel"><h2>升學意向</h2><p className="muted">申請國家可複選；各校實際申請請在「選校與申請」分別建立。</p><Choice label="申請國家／地區（可複選）" value={selected.countries} onChange={(v:string[])=>update('countries',v)} options={countries} multi array/><Choice label="志願科系（依留學 DIY 導航，可複選）" value={selected.major} onChange={(v:string)=>update('major',v)} options={majorOptions} multi/><div className="form-grid"><Choice label="升學目標" value={selected.goal} options={diyOptions['start-goal'].slice(1)} onChange={(v:string)=>update('goal',v)}/><Choice label="年度學費預算" value={selected.budget} options={diyOptions['start-budget'].slice(1)} onChange={(v:string)=>update('budget',v)}/><Choice label="目前最需要的協助" value={selected.need} options={diyOptions['start-need'].slice(1)} onChange={(v:string)=>update('need',v)}/></div><Field label="需要確認的事項（確認後可清空）" value={selected.review} onChange={(v:string)=>update('review',v)} large/></section></TabsContent>
 <TabsContent value="applications"><section className="panel"><div className="section-head"><div><h2>每一所學校，獨立追蹤</h2><p className="muted">錄取、住宿與簽證可以同時進行，各自保留日期及進度。</p></div><Button onClick={addApp}><Plus size={16}/>新增選校</Button></div>{!active?<div className="empty"><Globe2 size={34}/><h3>尚未建立選校申請</h3><p>先加入大學與科系，再記錄申請條件、費用與每一步進度。</p></div>:<><div className="app-pills">{selected.applications.map((a:any,i:number)=><Button key={a.id} variant={i===appIndex?'default':'outline'} onClick={()=>setAppIndex(i)}>{a.university||'未命名選校'}{a.program?' · '+a.program:''}</Button>)}</div><div className="form-grid"><label className="field"><span>申請國家</span><Choice value={active.country} onChange={(v:string)=>changeApp('country',v)} options={['待確認',...countries]} label="申請國家"/></label><label className="field"><span>申請／錄取狀態</span><Pick value={active.status} onChange={(v:string)=>changeApp('status',v)} options={stages} label="申請狀態"/></label><label className="field"><span>簽證進度</span><Pick value={active.visaStatus} onChange={(v:string)=>changeApp('visaStatus',v)} options={['未開始','準備文件','已送件','待面談／生物辨識','補件中','已核准','不適用','拒簽／撤回']} label="簽證進度"/></label></div>{[['學校與入學要求',0,10],['申請平台與送件',10,15],['學費與查核來源',15,23],['錄取、補件與接受',23,32],['宿舍安排',32,36],['簽證到行前準備',36,48]].map(([title,start,end]:any)=><details className="app-section" open key={title}><summary>{title}</summary><div className="form-grid">{applicationFields.slice(start,end).map(([k,l])=><SmartField key={k} options={k==='university'?universityOptions.filter(u=>u.country===active.country||(['德國','荷蘭','其他歐洲'].includes(active.country)&&u.country==='歐洲')).map(u=>u.name):undefined} label={l} value={active[k]} onChange={(v:string)=>changeApp(k,v)} large={/Requirement|materials|Notes|conditions$|Documents|Steps|postVisa|supplementStatus/.test(k)} type={/^(deadline|checkedAt|submittedAt|offerDate|conditionsDeadline|unconditionalDate|acceptanceDeadline|accommodationDeadline|visaSubmitted|visaApproved|visaExpiry|arrival|nextDue)$/.test(k)?'date':'text'}/>)}</div></details>)}<p className="muted">費用尚未查核時請留白。官方最低門檻與實際競爭分數應分別註明。</p></>}</section></TabsContent>
 <TabsContent value="advice"><section className="panel ai-panel"><div className="section-head"><div><div className="eyebrow"><Sparkles size={15}/>個人化準備方向</div><h2>從志願，整理下一步</h2></div><Button onClick={generate} disabled={aiBusy||!meta.aiReady}>{aiBusy?'正在查詢與整理…':'產生 AI 建議'}</Button></div>{!meta.aiReady&&<p className="notice">AI 連線尚未啟用。以下為依已填資料整理的準備清單，不是即時 AI 查詢結果。</p>}<ul className="recommendations">{preparation(selected).map(x=><li key={x}><CheckCircle2 size={17}/>{x}</li>)}</ul>{selected.advice&&<div className="ai-result"><small>AI 草稿 · {selected.advice.createdAt} · 請核對引用來源與入學年度</small><pre>{selected.advice.text}</pre>{selected.advice.sources?.map((s:any,i:number)=><div key={i}><Link url={s.url}>{s.title||s.url}</Link></div>)}</div>}</section>
 {selected.countries.length===0?<section className="panel">請先選擇申請國家，再查看準備指南。</section>:selected.countries.map((c:string)=>{const g=guide[c]||fallback;return <section className="panel guide" key={c}><h2><Globe2 size={20}/>{c}申請指南</h2><div className="guide-grid"><div><h3>資格與課程準備</h3><p>{g.entry}</p><Link url={g.entryUrl}>資格參考</Link><h3>平台與時間</h3><p>{g.platform}</p><p>{g.timing}</p><Link url={g.url}>申請平台／官方說明</Link></div><div><h3>簽證文件與流程</h3><p>{g.visa}</p><Link url={g.visaUrl}>官方簽證說明</Link><Link url={g.applyUrl}>簽證申請入口</Link><h3>核准後</h3><p>{g.after}</p></div></div><small>指南整理：2026/09/19。申請前重新核對官方規定；個別身分與科系可能不同。</small></section>})}</TabsContent>
 <TabsContent value="notes"><section className="panel"><h2>新增輔導紀錄</h2><p className="muted">點選麥克風說話，文字辨識完成後可修改。按加入後再儲存學生紀錄。</p><div className="form-grid"><Field label="輔導日期" type="date" value={noteDate} onChange={setNoteDate}/><Field label="下次追蹤日期" type="date" value={noteDue} onChange={setNoteDue}/><Field label="訪談重點、決定與待辦" value={note} onChange={setNote} large/></div><Button onClick={()=>{if(!note.trim()){toast.error('請先輸入紀錄');return}update('notes',[{id:crypto.randomUUID(),date:noteDate,text:note,nextDue:noteDue},...selected.notes]);setNote('');setNoteDue('');toast.success('已加入，請儲存紀錄')}}>加入輔導紀錄</Button></section>{selected.notes.map((n:any)=><section className="panel note" key={n.id}><div className="eyebrow">{n.date} {n.nextDue&&'／下次追蹤 '+n.nextDue}</div><p>{n.text}</p></section>)}</TabsContent>
 <TabsContent value="consultations">{!selected.consultations?.length?<section className="panel">尚無個別諮詢調查回覆。</section>:selected.consultations.map((c:any)=><section className="panel" key={c.id}><div className="section-head"><div><h2>Peter 總監個別諮詢調查</h2><p className="muted">回覆時間：{c.submittedAt}　／　{c.sourceSheet} 第 {c.sourceRow} 列</p></div><span className="badge warning">意願時段，尚未確認預約</span></div><div className="guide-grid"><div><h3>聯絡與班級</h3><p>班級：{c.className}　座號：{c.seat}<br/>學生電話：{c.phone}<br/>學生 Email：{c.email}<br/>家長電話：{c.parentPhone}<br/>陪同家長：{c.parent||'未填'}</p><h3>最新自填志願與成績</h3><p>國家：{c.countries.join('、')}<br/>科系：{c.major}<br/>高中四學期平均：{c.average}<br/>英語檢定：{c.englishStatus}；{c.english}</p><Button variant="outline" onClick={()=>{setSelected((s:any)=>({...s,countries:Array.from(new Set([...s.countries,...c.countries])),major:c.major||c.fields,taiwanAverage:c.average+'（高中四學期，自填）',ielts:[c.englishStatus,c.english].join('；')}));setDirty(true);toast.success('已帶入基本資料，請檢查後儲存。')}}>將本次志願與成績帶入基本資料</Button></div><div><h3>諮詢時段偏好</h3>{c.slots.map((v:string,i:number)=><p key={i}><b>第 {i+1} 優先</b><br/>{v||'未填'}</p>)}<h3>希望協助事項</h3><p>{c.needs}</p><h3>想詢問的問題</h3><p>{c.questions||'未填'}</p></div></div><details className="app-section"><summary>完整原始回覆（含活動經歷與家長意見）</summary><Table><TableHeader><TableRow><TableHead>題目</TableHead><TableHead>回覆</TableHead></TableRow></TableHeader><TableBody>{c.raw.map((r:any)=><TableRow key={r.cell}><TableCell>{r.label}<small>{r.cell}</small></TableCell><TableCell className="whitespace-pre-wrap">{r.value}</TableCell></TableRow>)}</TableBody></Table></details></section>)}</TabsContent><TabsContent value="source"><section className="panel"><h2>原始調查內容</h2><p className="muted">{selected.sourceSheet||'手動新增'}{selected.sourceRow&&` 工作表，第 ${selected.sourceRow} 列`}。保留原始儲存格，不自動把無標題欄的校名當成已確認志願。</p><Table><TableHeader><TableRow><TableHead>儲存格</TableHead><TableHead>原文</TableHead></TableRow></TableHeader><TableBody>{selected.raw.map((r:any)=><TableRow key={r.cell}><TableCell>{r.cell}</TableCell><TableCell className="whitespace-pre-wrap">{r.value}</TableCell></TableRow>)}</TableBody></Table></section></TabsContent></Tabs></fieldset>
 </>:view==='review'?<><div className="page-heading"><div className="eyebrow">資料核對</div><h1>待確認資料</h1><p>先核對歸屬與年度，再更新學生資料。</p></div><section className="panel"><h2>未署名紀錄 · {meta.unassigned?.length||0} 筆</h2>{meta.unassigned?.map((r:any)=><p key={r.row}>2026 表第 {r.row} 列：{r.values.filter(Boolean).join(' ／ ')}</p>)}<p className="muted">未合併至任何學生，避免誤植。</p></section><section className="panel"><h2>姓名異字與手填資料</h2><p>「簡士植」與「簡仕植」目前保留為兩筆，請先確認是否同一人。部分手填列有國家、科系與高中混欄，請對照原始儲存格。</p><p>2025 表 {meta.archiveSheets?.[0]?.rows} 筆、2024 表 {meta.archiveSheets?.[1]?.rows} 筆目前未混入本屆；2026 表年度不等同已確認畢業年度。</p></section></>:view==='tracking'?<><div className="page-heading"><div className="eyebrow">APPLICATION TRACKER</div><h1>申請進度總覽</h1><p>逐校追蹤送件、錄取、補件、宿舍與簽證。</p></div><section className="panel">{apps.length?<Table><TableHeader><TableRow>{['學生','學校／科系','錄取進度','宿舍','簽證','下一步／期限'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{apps.map(a=><TableRow key={a.id} onClick={()=>{choose(a.student);setTab('applications');setAppIndex(a.student.applications.findIndex((x:any)=>x.id===a.id))}} className="clickable"><TableCell>{a.student.name}</TableCell><TableCell>{a.university}<small>{a.program}</small></TableCell><TableCell>{a.status}</TableCell><TableCell>{a.accommodation||'未填'}</TableCell><TableCell>{a.visaStatus}</TableCell><TableCell>{a.nextAction||'待安排'}<small>{a.nextDue||a.deadline}</small></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><ClipboardList size={35}/><h3>尚未建立申請案件</h3><p>從學生名單進入個人資料，新增第一所選校。</p><Button onClick={()=>setView('students')}>查看學生名單</Button></div>}</section></>:<>
 <div className="page-heading"><div className="eyebrow">LTU EDUCATION · COUNSELLING</div><h1>學生升學工作台</h1><p>從選校到出發，把每位同學的下一步記清楚。</p></div><div className="stats"><div><span>已建檔學生</span><strong>{students.length}<small>筆</small></strong><Users/></div><div><span>已有選校申請</span><strong>{students.filter(s=>s.applications.length).length}<small>位</small></strong><Globe2/></div><div><span>待核對紀錄</span><strong>{students.filter(s=>s.review).length}<small>筆</small></strong><AlertCircle/></div><div><span>輔導紀錄</span><strong>{students.reduce((n,s)=>n+s.notes.length,0)}<small>筆</small></strong><ClipboardList/></div></div>
 <section className="panel roster"><div className="section-head"><div><h2>學生名單 <span className="count">{filtered.length}</span></h2><p className="muted">升學意向＋個別諮詢調查 · 年級與入學年度請逐一確認</p></div></div><div className="filters"><div className="search"><Search size={18}/><Input placeholder="搜尋姓名、英文暱稱、高中或科系…" value={q} onChange={e=>setQ(e.target.value)}/></div><Pick value={country} onChange={setCountry} options={['全部國家',...countries]} label="國家篩選"/></div><Table><TableHeader><TableRow>{['學生','就讀高中','申請國家','志願科系／學群','建檔狀態',''].map((x,i)=><TableHead key={i}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(s=><TableRow key={s.id} className="clickable" onClick={()=>choose(s)}><TableCell><div className="name-cell"><span className="mini-avatar">{s.name.slice(0,1)}</span><div><b>{s.name}</b><small>{s.nickname||'—'}</small></div></div></TableCell><TableCell>{s.school||'待確認'}</TableCell><TableCell><div className="tags">{s.countries.length?s.countries.slice(0,3).map((c:string)=><span key={c}>{c}</span>):<span>待確認</span>}{s.countries.length>3&&<span>+{s.countries.length-3}</span>}</div></TableCell><TableCell><div className="major">{s.major||'尚未填寫'}</div></TableCell><TableCell><span className={s.review?'badge warning':'badge'}>{s.consultations?.length?'有諮詢回覆':s.review?'待核對':'已確認'}</span></TableCell><TableCell><Button variant="ghost" onClick={e=>{e.stopPropagation();choose(s)}}>開啟 →</Button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<div className="empty">找不到符合條件的學生。</div>}</section></>}
 <footer>LTU OSSD 升學輔導　<span>學生資料僅供內部輔導使用</span></footer></main></div></div>
}
